CREATE TABLE m_recoverable_exception_type_setting(
  recoverable_exception_type INTEGER NOT NULL,
  title TEXT NOT NULL,
  message TEXT NOT NULL,
  button_text TEXT NOT NULL,
  transition_id INTEGER,
  transition_parameter INTEGER,
  is_transition_back INTEGER NOT NULL,
  PRIMARY KEY (recoverable_exception_type)
);
INSERT INTO `m_recoverable_exception_type_setting` VALUES (/*recoverable_exception_type*/1, /*title*/"k.m_gacha_out_of_term_title", /*message*/"k.m_gacha_out_of_term_message", /*button_text*/"k.common_l_p503", /*transition_id*/"", /*transition_parameter*/"", /*is_transition_back*/0);
INSERT INTO `m_recoverable_exception_type_setting` VALUES (/*recoverable_exception_type*/2, /*title*/"k.m_gacha_daily_limit_title", /*message*/"k.m_gacha_daily_limit_message", /*button_text*/"k.common_l_p503", /*transition_id*/"", /*transition_parameter*/"", /*is_transition_back*/0);
INSERT INTO `m_recoverable_exception_type_setting` VALUES (/*recoverable_exception_type*/3, /*title*/"k.m_gacha_retry_out_of_term_title", /*message*/"k.m_gacha_retry_out_of_term_message", /*button_text*/"k.common_l_p503", /*transition_id*/"", /*transition_parameter*/"", /*is_transition_back*/0);
INSERT INTO `m_recoverable_exception_type_setting` VALUES (/*recoverable_exception_type*/4, /*title*/"k.m_shop_item_out_of_term_title", /*message*/"k.m_shop_item_out_of_term_message", /*button_text*/"k.common_l_p503", /*transition_id*/36, /*transition_parameter*/"", /*is_transition_back*/0);
INSERT INTO `m_recoverable_exception_type_setting` VALUES (/*recoverable_exception_type*/5, /*title*/"k.m_shop_event_out_of_term_title", /*message*/"k.m_shop_event_out_of_term_message", /*button_text*/"k.common_l_p503", /*transition_id*/40, /*transition_parameter*/"", /*is_transition_back*/0);
INSERT INTO `m_recoverable_exception_type_setting` VALUES (/*recoverable_exception_type*/6, /*title*/"k.m_shop_shop_item_all_expired_title", /*message*/"k.m_shop_shop_item_all_expired_message", /*button_text*/"k.common_l_p503", /*transition_id*/12, /*transition_parameter*/"", /*is_transition_back*/0);
INSERT INTO `m_recoverable_exception_type_setting` VALUES (/*recoverable_exception_type*/7, /*title*/"k.m_shop_event_all_expired_title", /*message*/"k.m_shop_event_all_expired_message", /*button_text*/"k.common_l_p503", /*transition_id*/12, /*transition_parameter*/"", /*is_transition_back*/0);
INSERT INTO `m_recoverable_exception_type_setting` VALUES (/*recoverable_exception_type*/8, /*title*/"k.m_shop_lp_limit_exceeded_title", /*message*/"k.m_shop_lp_limit_exceeded_message", /*button_text*/"k.common_l_p503", /*transition_id*/"", /*transition_parameter*/"", /*is_transition_back*/0);
INSERT INTO `m_recoverable_exception_type_setting` VALUES (/*recoverable_exception_type*/9, /*title*/"k.m_shop_ap_limit_exceeded_title", /*message*/"k.m_shop_ap_limit_exceeded_message", /*button_text*/"k.common_l_p503", /*transition_id*/"", /*transition_parameter*/"", /*is_transition_back*/0);
INSERT INTO `m_recoverable_exception_type_setting` VALUES (/*recoverable_exception_type*/10, /*title*/"k.m_name_contains_ng_word_title", /*message*/"k.m_name_contains_ng_word_message", /*button_text*/"k.common_l_p503", /*transition_id*/"", /*transition_parameter*/"", /*is_transition_back*/0);
INSERT INTO `m_recoverable_exception_type_setting` VALUES (/*recoverable_exception_type*/11, /*title*/"k.m_nickname_contains_ng_word_title", /*message*/"k.m_nickname_contains_ng_word_message", /*button_text*/"k.common_l_p503", /*transition_id*/"", /*transition_parameter*/"", /*is_transition_back*/0);
INSERT INTO `m_recoverable_exception_type_setting` VALUES (/*recoverable_exception_type*/12, /*title*/"k.m_message_contains_ng_word_title", /*message*/"k.m_message_contains_ng_word_message", /*button_text*/"k.common_l_p503", /*transition_id*/"", /*transition_parameter*/"", /*is_transition_back*/0);
INSERT INTO `m_recoverable_exception_type_setting` VALUES (/*recoverable_exception_type*/13, /*title*/"k.exception_l_p301", /*message*/"k.exception_l_p302", /*button_text*/"k.common_l_p503", /*transition_id*/"", /*transition_parameter*/"", /*is_transition_back*/0);
INSERT INTO `m_recoverable_exception_type_setting` VALUES (/*recoverable_exception_type*/14, /*title*/"k.shop_l_p2601", /*message*/"k.shop_l_p2602", /*button_text*/"k.common_l_p503", /*transition_id*/"", /*transition_parameter*/"", /*is_transition_back*/0);
INSERT INTO `m_recoverable_exception_type_setting` VALUES (/*recoverable_exception_type*/15, /*title*/"k.exception_l_p101", /*message*/"k.exception_l_p102", /*button_text*/"k.common_l_p503", /*transition_id*/"", /*transition_parameter*/"", /*is_transition_back*/0);
INSERT INTO `m_recoverable_exception_type_setting` VALUES (/*recoverable_exception_type*/16, /*title*/"k.exception_l_p201", /*message*/"k.exception_l_p202", /*button_text*/"k.common_l_p503", /*transition_id*/"", /*transition_parameter*/"", /*is_transition_back*/0);
INSERT INTO `m_recoverable_exception_type_setting` VALUES (/*recoverable_exception_type*/17, /*title*/"k.exception_l_p501", /*message*/"k.exception_l_p502", /*button_text*/"k.common_l_p503", /*transition_id*/"", /*transition_parameter*/"", /*is_transition_back*/0);
INSERT INTO `m_recoverable_exception_type_setting` VALUES (/*recoverable_exception_type*/18, /*title*/"k.exception_l_p601", /*message*/"k.exception_l_p602", /*button_text*/"k.common_l_p503", /*transition_id*/"", /*transition_parameter*/"", /*is_transition_back*/0);
INSERT INTO `m_recoverable_exception_type_setting` VALUES (/*recoverable_exception_type*/19, /*title*/"k.exception_l_p701", /*message*/"k.exception_l_p702", /*button_text*/"k.common_l_p503", /*transition_id*/"", /*transition_parameter*/"", /*is_transition_back*/0);
INSERT INTO `m_recoverable_exception_type_setting` VALUES (/*recoverable_exception_type*/20, /*title*/"k.exception_l_p801", /*message*/"k.exception_l_p802", /*button_text*/"k.common_l_p503", /*transition_id*/"", /*transition_parameter*/"", /*is_transition_back*/0);
INSERT INTO `m_recoverable_exception_type_setting` VALUES (/*recoverable_exception_type*/21, /*title*/"k.event_marathon_l_p801", /*message*/"k.event_marathon_l_p802", /*button_text*/"k.common_l_p503", /*transition_id*/12, /*transition_parameter*/"", /*is_transition_back*/0);
INSERT INTO `m_recoverable_exception_type_setting` VALUES (/*recoverable_exception_type*/22, /*title*/"k.shop_l_p2901", /*message*/"k.shop_l_p2902", /*button_text*/"k.common_l_p503", /*transition_id*/"", /*transition_parameter*/"", /*is_transition_back*/0);
INSERT INTO `m_recoverable_exception_type_setting` VALUES (/*recoverable_exception_type*/23, /*title*/"k.common_l_p101", /*message*/"k.common_l_p102", /*button_text*/"k.common_l_p503", /*transition_id*/"", /*transition_parameter*/"", /*is_transition_back*/0);
INSERT INTO `m_recoverable_exception_type_setting` VALUES (/*recoverable_exception_type*/24, /*title*/"k.shop_l_p301", /*message*/"k.shop_l_p302", /*button_text*/"k.common_l_p503", /*transition_id*/"", /*transition_parameter*/"", /*is_transition_back*/0);
INSERT INTO `m_recoverable_exception_type_setting` VALUES (/*recoverable_exception_type*/25, /*title*/"k.tutorial_l_p1401", /*message*/"k.tutorial_l_p1402", /*button_text*/"k.common_l_p503", /*transition_id*/"", /*transition_parameter*/"", /*is_transition_back*/0);
INSERT INTO `m_recoverable_exception_type_setting` VALUES (/*recoverable_exception_type*/26, /*title*/"k.tutorial_l_p1401", /*message*/"k.tutorial_l_p1403", /*button_text*/"k.common_l_p503", /*transition_id*/"", /*transition_parameter*/"", /*is_transition_back*/0);
INSERT INTO `m_recoverable_exception_type_setting` VALUES (/*recoverable_exception_type*/28, /*title*/"k.exception_l_p701", /*message*/"k.exception_l_p702", /*button_text*/"k.common_l_p503", /*transition_id*/"", /*transition_parameter*/"", /*is_transition_back*/1);
INSERT INTO `m_recoverable_exception_type_setting` VALUES (/*recoverable_exception_type*/29, /*title*/"k.exception_l_p801", /*message*/"k.exception_l_p802", /*button_text*/"k.common_l_p503", /*transition_id*/"", /*transition_parameter*/"", /*is_transition_back*/1);
INSERT INTO `m_recoverable_exception_type_setting` VALUES (/*recoverable_exception_type*/30, /*title*/"k.m_mission_out_of_date_title", /*message*/"k.m_mission_out_of_date_message", /*button_text*/"k.common_l_p503", /*transition_id*/"", /*transition_parameter*/"", /*is_transition_back*/0);
