CREATE TABLE m_story_main_cell(
  id INTEGER NOT NULL,
  chapter_id INTEGER NOT NULL,
  display_order INTEGER NOT NULL,
  number INTEGER,
  type INTEGER NOT NULL,
  index_text TEXT NOT NULL,
  title TEXT NOT NULL,
  summary TEXT NOT NULL,
  member_group INTEGER NOT NULL,
  thumbnail_asset_path TEXT,
  popup_thumbnail_asset_path TEXT,
  scenario_script_asset_path TEXT,
  movie_asset_path TEXT,
  live_difficulty_id INTEGER,
  unlock_live_id TEXT,
  live_icon_asset_path TEXT,
  transformation_reference_cell_id INTEGER,
  PRIMARY KEY (id),
  UNIQUE (chapter_id, display_order)
);
INSERT INTO `m_story_main_cell` VALUES (/*id*/1001, /*chapter_id*/1, /*display_order*/1, /*number*/1, /*type*/1, /*index_text*/"m.story_index_title_1a", /*title*/"m.story_main_title_1_1a", /*summary*/"m.story_main_summary_1_1a", /*member_group*/100, /*thumbnail_asset_path*/"..V", /*popup_thumbnail_asset_path*/"w\"p", /*scenario_script_asset_path*/"MS/001/ms_001_01a", /*movie_asset_path*/"", /*live_difficulty_id*/"", /*unlock_live_id*/"", /*live_icon_asset_path*/"", /*transformation_reference_cell_id*/"");
INSERT INTO `m_story_main_cell` VALUES (/*id*/1002, /*chapter_id*/1, /*display_order*/2, /*number*/"", /*type*/2, /*index_text*/"k.dummy", /*title*/"k.dummy", /*summary*/"k.dummy", /*member_group*/1, /*thumbnail_asset_path*/"", /*popup_thumbnail_asset_path*/"", /*scenario_script_asset_path*/"", /*movie_asset_path*/"", /*live_difficulty_id*/30001301, /*unlock_live_id*/10001, /*live_icon_asset_path*/"", /*transformation_reference_cell_id*/"");
INSERT INTO `m_story_main_cell` VALUES (/*id*/1003, /*chapter_id*/1, /*display_order*/3, /*number*/1, /*type*/1, /*index_text*/"m.story_index_title_1b", /*title*/"m.story_main_title_1_1b", /*summary*/"m.story_main_summary_1_1b", /*member_group*/100, /*thumbnail_asset_path*/"*[I", /*popup_thumbnail_asset_path*/"4/K", /*scenario_script_asset_path*/"MS/001/ms_001_01b", /*movie_asset_path*/"", /*live_difficulty_id*/"", /*unlock_live_id*/"", /*live_icon_asset_path*/"", /*transformation_reference_cell_id*/"");
INSERT INTO `m_story_main_cell` VALUES (/*id*/1004, /*chapter_id*/1, /*display_order*/4, /*number*/"", /*type*/2, /*index_text*/"k.dummy", /*title*/"k.dummy", /*summary*/"k.dummy", /*member_group*/2, /*thumbnail_asset_path*/"", /*popup_thumbnail_asset_path*/"", /*scenario_script_asset_path*/"", /*movie_asset_path*/"", /*live_difficulty_id*/31007301, /*unlock_live_id*/11007, /*live_icon_asset_path*/"", /*transformation_reference_cell_id*/"");
INSERT INTO `m_story_main_cell` VALUES (/*id*/1005, /*chapter_id*/1, /*display_order*/5, /*number*/"", /*type*/2, /*index_text*/"k.dummy", /*title*/"k.dummy", /*summary*/"k.dummy", /*member_group*/2, /*thumbnail_asset_path*/"", /*popup_thumbnail_asset_path*/"", /*scenario_script_asset_path*/"", /*movie_asset_path*/"", /*live_difficulty_id*/31001101, /*unlock_live_id*/11001, /*live_icon_asset_path*/"", /*transformation_reference_cell_id*/"");
INSERT INTO `m_story_main_cell` VALUES (/*id*/1006, /*chapter_id*/1, /*display_order*/6, /*number*/2, /*type*/1, /*index_text*/"m.story_index_title_2", /*title*/"m.story_main_title_1_2", /*summary*/"m.story_main_summary_1_2", /*member_group*/100, /*thumbnail_asset_path*/"rMD", /*popup_thumbnail_asset_path*/"CbD", /*scenario_script_asset_path*/"MS/001/ms_001_02", /*movie_asset_path*/"", /*live_difficulty_id*/"", /*unlock_live_id*/"", /*live_icon_asset_path*/"", /*transformation_reference_cell_id*/"");
INSERT INTO `m_story_main_cell` VALUES (/*id*/1007, /*chapter_id*/1, /*display_order*/7, /*number*/3, /*type*/1, /*index_text*/"m.story_index_title_3", /*title*/"m.story_main_title_1_3", /*summary*/"m.story_main_summary_1_3", /*member_group*/100, /*thumbnail_asset_path*/"1km", /*popup_thumbnail_asset_path*/"<Em", /*scenario_script_asset_path*/"MS/001/ms_001_03", /*movie_asset_path*/"", /*live_difficulty_id*/"", /*unlock_live_id*/"", /*live_icon_asset_path*/"", /*transformation_reference_cell_id*/"");
INSERT INTO `m_story_main_cell` VALUES (/*id*/1008, /*chapter_id*/1, /*display_order*/8, /*number*/"", /*type*/2, /*index_text*/"k.dummy", /*title*/"k.dummy", /*summary*/"k.dummy", /*member_group*/1, /*thumbnail_asset_path*/"", /*popup_thumbnail_asset_path*/"", /*scenario_script_asset_path*/"", /*movie_asset_path*/"", /*live_difficulty_id*/30001101, /*unlock_live_id*/10001, /*live_icon_asset_path*/"", /*transformation_reference_cell_id*/"");
INSERT INTO `m_story_main_cell` VALUES (/*id*/1009, /*chapter_id*/1, /*display_order*/9, /*number*/4, /*type*/1, /*index_text*/"m.story_index_title_4", /*title*/"m.story_main_title_1_4", /*summary*/"m.story_main_summary_1_4", /*member_group*/100, /*thumbnail_asset_path*/"P{1", /*popup_thumbnail_asset_path*/"Kms", /*scenario_script_asset_path*/"MS/001/ms_001_04", /*movie_asset_path*/"", /*live_difficulty_id*/"", /*unlock_live_id*/"", /*live_icon_asset_path*/"", /*transformation_reference_cell_id*/"");
INSERT INTO `m_story_main_cell` VALUES (/*id*/1010, /*chapter_id*/1, /*display_order*/10, /*number*/5, /*type*/1, /*index_text*/"m.story_index_title_5", /*title*/"m.story_main_title_1_5", /*summary*/"m.story_main_summary_1_5", /*member_group*/100, /*thumbnail_asset_path*/"V'G", /*popup_thumbnail_asset_path*/"0R(", /*scenario_script_asset_path*/"MS/001/ms_001_05", /*movie_asset_path*/"", /*live_difficulty_id*/"", /*unlock_live_id*/"", /*live_icon_asset_path*/"", /*transformation_reference_cell_id*/"");
INSERT INTO `m_story_main_cell` VALUES (/*id*/1011, /*chapter_id*/1, /*display_order*/11, /*number*/"", /*type*/2, /*index_text*/"k.dummy", /*title*/"k.dummy", /*summary*/"k.dummy", /*member_group*/2, /*thumbnail_asset_path*/"", /*popup_thumbnail_asset_path*/"", /*scenario_script_asset_path*/"", /*movie_asset_path*/"", /*live_difficulty_id*/31007101, /*unlock_live_id*/11007, /*live_icon_asset_path*/"", /*transformation_reference_cell_id*/"");
INSERT INTO `m_story_main_cell` VALUES (/*id*/1012, /*chapter_id*/1, /*display_order*/12, /*number*/6, /*type*/1, /*index_text*/"m.story_index_title_6", /*title*/"m.story_main_title_1_6", /*summary*/"m.story_main_summary_1_6", /*member_group*/100, /*thumbnail_asset_path*/"T`d", /*popup_thumbnail_asset_path*/"KN'", /*scenario_script_asset_path*/"MS/001/ms_001_06", /*movie_asset_path*/"", /*live_difficulty_id*/"", /*unlock_live_id*/"", /*live_icon_asset_path*/"", /*transformation_reference_cell_id*/"");
INSERT INTO `m_story_main_cell` VALUES (/*id*/1013, /*chapter_id*/1, /*display_order*/13, /*number*/7, /*type*/1, /*index_text*/"m.story_index_title_7", /*title*/"m.story_main_title_1_7", /*summary*/"m.story_main_summary_1_7", /*member_group*/100, /*thumbnail_asset_path*/"{08", /*popup_thumbnail_asset_path*/"d%x", /*scenario_script_asset_path*/"MS/001/ms_001_07", /*movie_asset_path*/"", /*live_difficulty_id*/"", /*unlock_live_id*/"", /*live_icon_asset_path*/"", /*transformation_reference_cell_id*/"");
INSERT INTO `m_story_main_cell` VALUES (/*id*/1014, /*chapter_id*/1, /*display_order*/14, /*number*/"", /*type*/2, /*index_text*/"k.dummy", /*title*/"k.dummy", /*summary*/"k.dummy", /*member_group*/1, /*thumbnail_asset_path*/"", /*popup_thumbnail_asset_path*/"", /*scenario_script_asset_path*/"", /*movie_asset_path*/"", /*live_difficulty_id*/30001199, /*unlock_live_id*/10001, /*live_icon_asset_path*/"", /*transformation_reference_cell_id*/"");
INSERT INTO `m_story_main_cell` VALUES (/*id*/1015, /*chapter_id*/1, /*display_order*/15, /*number*/8, /*type*/1, /*index_text*/"m.story_index_title_8", /*title*/"m.story_main_title_1_8", /*summary*/"m.story_main_summary_1_8", /*member_group*/100, /*thumbnail_asset_path*/"D-p", /*popup_thumbnail_asset_path*/"Y\"M", /*scenario_script_asset_path*/"MS/001/ms_001_08", /*movie_asset_path*/"", /*live_difficulty_id*/"", /*unlock_live_id*/"", /*live_icon_asset_path*/"", /*transformation_reference_cell_id*/"");
INSERT INTO `m_story_main_cell` VALUES (/*id*/1016, /*chapter_id*/1, /*display_order*/16, /*number*/9, /*type*/1, /*index_text*/"m.story_index_title_9", /*title*/"m.story_main_title_1_9", /*summary*/"m.story_main_summary_1_9", /*member_group*/100, /*thumbnail_asset_path*/"$RD", /*popup_thumbnail_asset_path*/"xT$", /*scenario_script_asset_path*/"MS/001/ms_001_09", /*movie_asset_path*/"", /*live_difficulty_id*/"", /*unlock_live_id*/"", /*live_icon_asset_path*/"", /*transformation_reference_cell_id*/"");
INSERT INTO `m_story_main_cell` VALUES (/*id*/1017, /*chapter_id*/1, /*display_order*/17, /*number*/"", /*type*/4, /*index_text*/"k.dummy", /*title*/"k.dummy", /*summary*/"k.dummy", /*member_group*/2, /*thumbnail_asset_path*/"", /*popup_thumbnail_asset_path*/"", /*scenario_script_asset_path*/"", /*movie_asset_path*/"", /*live_difficulty_id*/31001102, /*unlock_live_id*/11001, /*live_icon_asset_path*/"ob{", /*transformation_reference_cell_id*/"");
INSERT INTO `m_story_main_cell` VALUES (/*id*/1018, /*chapter_id*/1, /*display_order*/18, /*number*/10, /*type*/1, /*index_text*/"m.story_index_title_10", /*title*/"m.story_main_title_1_10", /*summary*/"m.story_main_summary_1_10", /*member_group*/100, /*thumbnail_asset_path*/"XfY", /*popup_thumbnail_asset_path*/"mw`", /*scenario_script_asset_path*/"MS/001/ms_001_10", /*movie_asset_path*/"", /*live_difficulty_id*/"", /*unlock_live_id*/"", /*live_icon_asset_path*/"", /*transformation_reference_cell_id*/"");
INSERT INTO `m_story_main_cell` VALUES (/*id*/2001, /*chapter_id*/2, /*display_order*/1, /*number*/1, /*type*/1, /*index_text*/"m.story_index_title_1", /*title*/"m.story_main_title_2_1", /*summary*/"m.story_main_summary_2_1", /*member_group*/100, /*thumbnail_asset_path*/"o@v", /*popup_thumbnail_asset_path*/"98A", /*scenario_script_asset_path*/"MS/002/ms_002_01", /*movie_asset_path*/"", /*live_difficulty_id*/"", /*unlock_live_id*/"", /*live_icon_asset_path*/"", /*transformation_reference_cell_id*/"");
INSERT INTO `m_story_main_cell` VALUES (/*id*/2002, /*chapter_id*/2, /*display_order*/2, /*number*/"", /*type*/2, /*index_text*/"k.dummy", /*title*/"k.dummy", /*summary*/"k.dummy", /*member_group*/1, /*thumbnail_asset_path*/"", /*popup_thumbnail_asset_path*/"", /*scenario_script_asset_path*/"", /*movie_asset_path*/"", /*live_difficulty_id*/30002101, /*unlock_live_id*/10002, /*live_icon_asset_path*/"", /*transformation_reference_cell_id*/"");
INSERT INTO `m_story_main_cell` VALUES (/*id*/2003, /*chapter_id*/2, /*display_order*/3, /*number*/2, /*type*/1, /*index_text*/"m.story_index_title_2", /*title*/"m.story_main_title_2_2", /*summary*/"m.story_main_summary_2_2", /*member_group*/100, /*thumbnail_asset_path*/"&@2", /*popup_thumbnail_asset_path*/"ZgD", /*scenario_script_asset_path*/"MS/002/ms_002_02", /*movie_asset_path*/"", /*live_difficulty_id*/"", /*unlock_live_id*/"", /*live_icon_asset_path*/"", /*transformation_reference_cell_id*/"");
INSERT INTO `m_story_main_cell` VALUES (/*id*/2004, /*chapter_id*/2, /*display_order*/4, /*number*/"", /*type*/2, /*index_text*/"k.dummy", /*title*/"k.dummy", /*summary*/"k.dummy", /*member_group*/1, /*thumbnail_asset_path*/"", /*popup_thumbnail_asset_path*/"", /*scenario_script_asset_path*/"", /*movie_asset_path*/"", /*live_difficulty_id*/30001201, /*unlock_live_id*/10001, /*live_icon_asset_path*/"", /*transformation_reference_cell_id*/"");
INSERT INTO `m_story_main_cell` VALUES (/*id*/2005, /*chapter_id*/2, /*display_order*/5, /*number*/3, /*type*/1, /*index_text*/"m.story_index_title_3", /*title*/"m.story_main_title_2_3", /*summary*/"m.story_main_summary_2_3", /*member_group*/100, /*thumbnail_asset_path*/"c[N", /*popup_thumbnail_asset_path*/"!q'", /*scenario_script_asset_path*/"MS/002/ms_002_03", /*movie_asset_path*/"", /*live_difficulty_id*/"", /*unlock_live_id*/"", /*live_icon_asset_path*/"", /*transformation_reference_cell_id*/"");
INSERT INTO `m_story_main_cell` VALUES (/*id*/2006, /*chapter_id*/2, /*display_order*/6, /*number*/4, /*type*/1, /*index_text*/"m.story_index_title_4", /*title*/"m.story_main_title_2_4", /*summary*/"m.story_main_summary_2_4", /*member_group*/100, /*thumbnail_asset_path*/"j_~", /*popup_thumbnail_asset_path*/"z$4", /*scenario_script_asset_path*/"MS/002/ms_002_04", /*movie_asset_path*/"", /*live_difficulty_id*/"", /*unlock_live_id*/"", /*live_icon_asset_path*/"", /*transformation_reference_cell_id*/"");
INSERT INTO `m_story_main_cell` VALUES (/*id*/2007, /*chapter_id*/2, /*display_order*/7, /*number*/"", /*type*/2, /*index_text*/"k.dummy", /*title*/"k.dummy", /*summary*/"k.dummy", /*member_group*/2, /*thumbnail_asset_path*/"", /*popup_thumbnail_asset_path*/"", /*scenario_script_asset_path*/"", /*movie_asset_path*/"", /*live_difficulty_id*/31001201, /*unlock_live_id*/11001, /*live_icon_asset_path*/"", /*transformation_reference_cell_id*/"");
INSERT INTO `m_story_main_cell` VALUES (/*id*/2008, /*chapter_id*/2, /*display_order*/8, /*number*/5, /*type*/1, /*index_text*/"m.story_index_title_5", /*title*/"m.story_main_title_2_5", /*summary*/"m.story_main_summary_2_5", /*member_group*/100, /*thumbnail_asset_path*/"QS8", /*popup_thumbnail_asset_path*/"[az", /*scenario_script_asset_path*/"MS/002/ms_002_05", /*movie_asset_path*/"", /*live_difficulty_id*/"", /*unlock_live_id*/"", /*live_icon_asset_path*/"", /*transformation_reference_cell_id*/"");
INSERT INTO `m_story_main_cell` VALUES (/*id*/2009, /*chapter_id*/2, /*display_order*/9, /*number*/6, /*type*/1, /*index_text*/"m.story_index_title_6", /*title*/"m.story_main_title_2_6", /*summary*/"m.story_main_summary_2_6", /*member_group*/100, /*thumbnail_asset_path*/"*F'", /*popup_thumbnail_asset_path*/"hz{", /*scenario_script_asset_path*/"MS/002/ms_002_06", /*movie_asset_path*/"", /*live_difficulty_id*/"", /*unlock_live_id*/"", /*live_icon_asset_path*/"", /*transformation_reference_cell_id*/"");
INSERT INTO `m_story_main_cell` VALUES (/*id*/2010, /*chapter_id*/2, /*display_order*/10, /*number*/"", /*type*/2, /*index_text*/"k.dummy", /*title*/"k.dummy", /*summary*/"k.dummy", /*member_group*/2, /*thumbnail_asset_path*/"", /*popup_thumbnail_asset_path*/"", /*scenario_script_asset_path*/"", /*movie_asset_path*/"", /*live_difficulty_id*/31007201, /*unlock_live_id*/11007, /*live_icon_asset_path*/"", /*transformation_reference_cell_id*/"");
INSERT INTO `m_story_main_cell` VALUES (/*id*/2011, /*chapter_id*/2, /*display_order*/11, /*number*/7, /*type*/1, /*index_text*/"m.story_index_title_7", /*title*/"m.story_main_title_2_7", /*summary*/"m.story_main_summary_2_7", /*member_group*/100, /*thumbnail_asset_path*/"qn'", /*popup_thumbnail_asset_path*/"MMi", /*scenario_script_asset_path*/"MS/002/ms_002_07", /*movie_asset_path*/"", /*live_difficulty_id*/"", /*unlock_live_id*/"", /*live_icon_asset_path*/"", /*transformation_reference_cell_id*/"");
INSERT INTO `m_story_main_cell` VALUES (/*id*/2012, /*chapter_id*/2, /*display_order*/12, /*number*/8, /*type*/1, /*index_text*/"m.story_index_title_8", /*title*/"m.story_main_title_2_8", /*summary*/"m.story_main_summary_2_8", /*member_group*/100, /*thumbnail_asset_path*/"Dle", /*popup_thumbnail_asset_path*/"rx_", /*scenario_script_asset_path*/"MS/002/ms_002_08", /*movie_asset_path*/"", /*live_difficulty_id*/"", /*unlock_live_id*/"", /*live_icon_asset_path*/"", /*transformation_reference_cell_id*/"");
INSERT INTO `m_story_main_cell` VALUES (/*id*/2013, /*chapter_id*/2, /*display_order*/13, /*number*/"", /*type*/2, /*index_text*/"k.dummy", /*title*/"k.dummy", /*summary*/"k.dummy", /*member_group*/1, /*thumbnail_asset_path*/"", /*popup_thumbnail_asset_path*/"", /*scenario_script_asset_path*/"", /*movie_asset_path*/"", /*live_difficulty_id*/30014101, /*unlock_live_id*/10014, /*live_icon_asset_path*/"", /*transformation_reference_cell_id*/"");
INSERT INTO `m_story_main_cell` VALUES (/*id*/2014, /*chapter_id*/2, /*display_order*/14, /*number*/9, /*type*/1, /*index_text*/"m.story_index_title_9", /*title*/"m.story_main_title_2_9", /*summary*/"m.story_main_summary_2_9", /*member_group*/100, /*thumbnail_asset_path*/"UY-", /*popup_thumbnail_asset_path*/"mZA", /*scenario_script_asset_path*/"MS/002/ms_002_09", /*movie_asset_path*/"", /*live_difficulty_id*/"", /*unlock_live_id*/"", /*live_icon_asset_path*/"", /*transformation_reference_cell_id*/"");
INSERT INTO `m_story_main_cell` VALUES (/*id*/2015, /*chapter_id*/2, /*display_order*/15, /*number*/"", /*type*/2, /*index_text*/"k.dummy", /*title*/"k.dummy", /*summary*/"k.dummy", /*member_group*/1, /*thumbnail_asset_path*/"", /*popup_thumbnail_asset_path*/"", /*scenario_script_asset_path*/"", /*movie_asset_path*/"", /*live_difficulty_id*/30001102, /*unlock_live_id*/10001, /*live_icon_asset_path*/"", /*transformation_reference_cell_id*/"");
INSERT INTO `m_story_main_cell` VALUES (/*id*/2016, /*chapter_id*/2, /*display_order*/16, /*number*/10, /*type*/1, /*index_text*/"m.story_index_title_10a", /*title*/"m.story_main_title_2_10a", /*summary*/"m.story_main_summary_2_10a", /*member_group*/100, /*thumbnail_asset_path*/"<?L", /*popup_thumbnail_asset_path*/"S%.", /*scenario_script_asset_path*/"MS/002/ms_002_10a", /*movie_asset_path*/"", /*live_difficulty_id*/"", /*unlock_live_id*/"", /*live_icon_asset_path*/"", /*transformation_reference_cell_id*/"");
INSERT INTO `m_story_main_cell` VALUES (/*id*/2017, /*chapter_id*/2, /*display_order*/17, /*number*/"", /*type*/4, /*index_text*/"k.dummy", /*title*/"k.dummy", /*summary*/"k.dummy", /*member_group*/3, /*thumbnail_asset_path*/"", /*popup_thumbnail_asset_path*/"", /*scenario_script_asset_path*/"", /*movie_asset_path*/"", /*live_difficulty_id*/32003301, /*unlock_live_id*/"12002,12003,12004,12005,12006,12007,12008,12009,12010", /*live_icon_asset_path*/"3RW", /*transformation_reference_cell_id*/2016);
INSERT INTO `m_story_main_cell` VALUES (/*id*/2018, /*chapter_id*/2, /*display_order*/18, /*number*/10, /*type*/1, /*index_text*/"m.story_index_title_10b", /*title*/"m.story_main_title_2_10b", /*summary*/"m.story_main_summary_2_10b", /*member_group*/100, /*thumbnail_asset_path*/"idS", /*popup_thumbnail_asset_path*/"vwP", /*scenario_script_asset_path*/"MS/002/ms_002_10b", /*movie_asset_path*/"", /*live_difficulty_id*/"", /*unlock_live_id*/"", /*live_icon_asset_path*/"", /*transformation_reference_cell_id*/"");
INSERT INTO `m_story_main_cell` VALUES (/*id*/3001, /*chapter_id*/3, /*display_order*/1, /*number*/1, /*type*/1, /*index_text*/"m.story_index_title_1", /*title*/"m.story_main_title_3_1", /*summary*/"m.story_main_summary_3_1", /*member_group*/100, /*thumbnail_asset_path*/"6u<", /*popup_thumbnail_asset_path*/"PG4", /*scenario_script_asset_path*/"MS/003/ms_003_01", /*movie_asset_path*/"", /*live_difficulty_id*/"", /*unlock_live_id*/"", /*live_icon_asset_path*/"", /*transformation_reference_cell_id*/"");
INSERT INTO `m_story_main_cell` VALUES (/*id*/3002, /*chapter_id*/3, /*display_order*/2, /*number*/"", /*type*/2, /*index_text*/"k.dummy", /*title*/"k.dummy", /*summary*/"k.dummy", /*member_group*/2, /*thumbnail_asset_path*/"", /*popup_thumbnail_asset_path*/"", /*scenario_script_asset_path*/"", /*movie_asset_path*/"", /*live_difficulty_id*/31002101, /*unlock_live_id*/11002, /*live_icon_asset_path*/"", /*transformation_reference_cell_id*/"");
INSERT INTO `m_story_main_cell` VALUES (/*id*/3003, /*chapter_id*/3, /*display_order*/3, /*number*/2, /*type*/1, /*index_text*/"m.story_index_title_2", /*title*/"m.story_main_title_3_2", /*summary*/"m.story_main_summary_3_2", /*member_group*/100, /*thumbnail_asset_path*/"gRR", /*popup_thumbnail_asset_path*/"q`6", /*scenario_script_asset_path*/"MS/003/ms_003_02", /*movie_asset_path*/"", /*live_difficulty_id*/"", /*unlock_live_id*/"", /*live_icon_asset_path*/"", /*transformation_reference_cell_id*/"");
INSERT INTO `m_story_main_cell` VALUES (/*id*/3004, /*chapter_id*/3, /*display_order*/4, /*number*/"", /*type*/2, /*index_text*/"k.dummy", /*title*/"k.dummy", /*summary*/"k.dummy", /*member_group*/2, /*thumbnail_asset_path*/"", /*popup_thumbnail_asset_path*/"", /*scenario_script_asset_path*/"", /*movie_asset_path*/"", /*live_difficulty_id*/31007102, /*unlock_live_id*/11007, /*live_icon_asset_path*/"", /*transformation_reference_cell_id*/"");
INSERT INTO `m_story_main_cell` VALUES (/*id*/3005, /*chapter_id*/3, /*display_order*/5, /*number*/3, /*type*/1, /*index_text*/"m.story_index_title_3", /*title*/"m.story_main_title_3_3", /*summary*/"m.story_main_summary_3_3", /*member_group*/100, /*thumbnail_asset_path*/"tK3", /*popup_thumbnail_asset_path*/"JsE", /*scenario_script_asset_path*/"MS/003/ms_003_03", /*movie_asset_path*/"", /*live_difficulty_id*/"", /*unlock_live_id*/"", /*live_icon_asset_path*/"", /*transformation_reference_cell_id*/"");
INSERT INTO `m_story_main_cell` VALUES (/*id*/3006, /*chapter_id*/3, /*display_order*/6, /*number*/"", /*type*/2, /*index_text*/"k.dummy", /*title*/"k.dummy", /*summary*/"k.dummy", /*member_group*/2, /*thumbnail_asset_path*/"", /*popup_thumbnail_asset_path*/"", /*scenario_script_asset_path*/"", /*movie_asset_path*/"", /*live_difficulty_id*/31006201, /*unlock_live_id*/11006, /*live_icon_asset_path*/"", /*transformation_reference_cell_id*/"");
INSERT INTO `m_story_main_cell` VALUES (/*id*/3007, /*chapter_id*/3, /*display_order*/7, /*number*/4, /*type*/1, /*index_text*/"m.story_index_title_4", /*title*/"m.story_main_title_3_4", /*summary*/"m.story_main_summary_3_4", /*member_group*/100, /*thumbnail_asset_path*/"=&D", /*popup_thumbnail_asset_path*/"#pi", /*scenario_script_asset_path*/"MS/003/ms_003_04", /*movie_asset_path*/"", /*live_difficulty_id*/"", /*unlock_live_id*/"", /*live_icon_asset_path*/"", /*transformation_reference_cell_id*/"");
INSERT INTO `m_story_main_cell` VALUES (/*id*/3008, /*chapter_id*/3, /*display_order*/8, /*number*/"", /*type*/2, /*index_text*/"k.dummy", /*title*/"k.dummy", /*summary*/"k.dummy", /*member_group*/2, /*thumbnail_asset_path*/"", /*popup_thumbnail_asset_path*/"", /*scenario_script_asset_path*/"", /*movie_asset_path*/"", /*live_difficulty_id*/31001103, /*unlock_live_id*/11001, /*live_icon_asset_path*/"", /*transformation_reference_cell_id*/"");
INSERT INTO `m_story_main_cell` VALUES (/*id*/3009, /*chapter_id*/3, /*display_order*/9, /*number*/5, /*type*/1, /*index_text*/"m.story_index_title_5", /*title*/"m.story_main_title_3_5", /*summary*/"m.story_main_summary_3_5", /*member_group*/100, /*thumbnail_asset_path*/"D*t", /*popup_thumbnail_asset_path*/"r6n", /*scenario_script_asset_path*/"MS/003/ms_003_05", /*movie_asset_path*/"", /*live_difficulty_id*/"", /*unlock_live_id*/"", /*live_icon_asset_path*/"", /*transformation_reference_cell_id*/"");
INSERT INTO `m_story_main_cell` VALUES (/*id*/3010, /*chapter_id*/3, /*display_order*/10, /*number*/"", /*type*/2, /*index_text*/"k.dummy", /*title*/"k.dummy", /*summary*/"k.dummy", /*member_group*/2, /*thumbnail_asset_path*/"", /*popup_thumbnail_asset_path*/"", /*scenario_script_asset_path*/"", /*movie_asset_path*/"", /*live_difficulty_id*/31005101, /*unlock_live_id*/11005, /*live_icon_asset_path*/"", /*transformation_reference_cell_id*/"");
INSERT INTO `m_story_main_cell` VALUES (/*id*/3011, /*chapter_id*/3, /*display_order*/11, /*number*/6, /*type*/1, /*index_text*/"m.story_index_title_6", /*title*/"m.story_main_title_3_6", /*summary*/"m.story_main_summary_3_6", /*member_group*/100, /*thumbnail_asset_path*/"A_9", /*popup_thumbnail_asset_path*/"iVb", /*scenario_script_asset_path*/"MS/003/ms_003_06", /*movie_asset_path*/"", /*live_difficulty_id*/"", /*unlock_live_id*/"", /*live_icon_asset_path*/"", /*transformation_reference_cell_id*/"");
INSERT INTO `m_story_main_cell` VALUES (/*id*/3012, /*chapter_id*/3, /*display_order*/12, /*number*/"", /*type*/2, /*index_text*/"k.dummy", /*title*/"k.dummy", /*summary*/"k.dummy", /*member_group*/3, /*thumbnail_asset_path*/"", /*popup_thumbnail_asset_path*/"", /*scenario_script_asset_path*/"", /*movie_asset_path*/"", /*live_difficulty_id*/32008101, /*unlock_live_id*/12008, /*live_icon_asset_path*/"", /*transformation_reference_cell_id*/"");
INSERT INTO `m_story_main_cell` VALUES (/*id*/3013, /*chapter_id*/3, /*display_order*/13, /*number*/7, /*type*/1, /*index_text*/"m.story_index_title_7", /*title*/"m.story_main_title_3_7", /*summary*/"m.story_main_summary_3_7", /*member_group*/100, /*thumbnail_asset_path*/"*t'", /*popup_thumbnail_asset_path*/"F+_", /*scenario_script_asset_path*/"MS/003/ms_003_07", /*movie_asset_path*/"", /*live_difficulty_id*/"", /*unlock_live_id*/"", /*live_icon_asset_path*/"", /*transformation_reference_cell_id*/"");
INSERT INTO `m_story_main_cell` VALUES (/*id*/3014, /*chapter_id*/3, /*display_order*/14, /*number*/"", /*type*/2, /*index_text*/"k.dummy", /*title*/"k.dummy", /*summary*/"k.dummy", /*member_group*/3, /*thumbnail_asset_path*/"", /*popup_thumbnail_asset_path*/"", /*scenario_script_asset_path*/"", /*movie_asset_path*/"", /*live_difficulty_id*/32004101, /*unlock_live_id*/12004, /*live_icon_asset_path*/"", /*transformation_reference_cell_id*/"");
INSERT INTO `m_story_main_cell` VALUES (/*id*/3015, /*chapter_id*/3, /*display_order*/15, /*number*/8, /*type*/1, /*index_text*/"m.story_index_title_8", /*title*/"m.story_main_title_3_8", /*summary*/"m.story_main_summary_3_8", /*member_group*/100, /*thumbnail_asset_path*/"i\"b", /*popup_thumbnail_asset_path*/"E_E", /*scenario_script_asset_path*/"MS/003/ms_003_08", /*movie_asset_path*/"", /*live_difficulty_id*/"", /*unlock_live_id*/"", /*live_icon_asset_path*/"", /*transformation_reference_cell_id*/"");
INSERT INTO `m_story_main_cell` VALUES (/*id*/3016, /*chapter_id*/3, /*display_order*/16, /*number*/"", /*type*/2, /*index_text*/"k.dummy", /*title*/"k.dummy", /*summary*/"k.dummy", /*member_group*/3, /*thumbnail_asset_path*/"", /*popup_thumbnail_asset_path*/"", /*scenario_script_asset_path*/"", /*movie_asset_path*/"", /*live_difficulty_id*/32003101, /*unlock_live_id*/12003, /*live_icon_asset_path*/"", /*transformation_reference_cell_id*/"");
INSERT INTO `m_story_main_cell` VALUES (/*id*/3017, /*chapter_id*/3, /*display_order*/17, /*number*/9, /*type*/1, /*index_text*/"m.story_index_title_9", /*title*/"m.story_main_title_3_9", /*summary*/"m.story_main_summary_3_9", /*member_group*/100, /*thumbnail_asset_path*/"<~A", /*popup_thumbnail_asset_path*/"LCU", /*scenario_script_asset_path*/"MS/003/ms_003_09", /*movie_asset_path*/"", /*live_difficulty_id*/"", /*unlock_live_id*/"", /*live_icon_asset_path*/"", /*transformation_reference_cell_id*/"");
INSERT INTO `m_story_main_cell` VALUES (/*id*/3018, /*chapter_id*/3, /*display_order*/18, /*number*/"", /*type*/4, /*index_text*/"k.dummy", /*title*/"k.dummy", /*summary*/"k.dummy", /*member_group*/2, /*thumbnail_asset_path*/"", /*popup_thumbnail_asset_path*/"", /*scenario_script_asset_path*/"", /*movie_asset_path*/"", /*live_difficulty_id*/31002102, /*unlock_live_id*/11002, /*live_icon_asset_path*/"JKb", /*transformation_reference_cell_id*/"");
INSERT INTO `m_story_main_cell` VALUES (/*id*/3019, /*chapter_id*/3, /*display_order*/19, /*number*/10, /*type*/1, /*index_text*/"m.story_index_title_10", /*title*/"m.story_main_title_3_10", /*summary*/"m.story_main_summary_3_10", /*member_group*/100, /*thumbnail_asset_path*/"3hn", /*popup_thumbnail_asset_path*/"M:f", /*scenario_script_asset_path*/"MS/003/ms_003_10", /*movie_asset_path*/"", /*live_difficulty_id*/"", /*unlock_live_id*/"", /*live_icon_asset_path*/"", /*transformation_reference_cell_id*/"");
INSERT INTO `m_story_main_cell` VALUES (/*id*/4001, /*chapter_id*/4, /*display_order*/1, /*number*/1, /*type*/1, /*index_text*/"m.story_index_title_1", /*title*/"m.story_main_title_4_1", /*summary*/"m.story_main_summary_4_1", /*member_group*/100, /*thumbnail_asset_path*/"8)_", /*popup_thumbnail_asset_path*/"\"[e", /*scenario_script_asset_path*/"MS/004/ms_004_01", /*movie_asset_path*/"", /*live_difficulty_id*/"", /*unlock_live_id*/"", /*live_icon_asset_path*/"", /*transformation_reference_cell_id*/"");
INSERT INTO `m_story_main_cell` VALUES (/*id*/4002, /*chapter_id*/4, /*display_order*/2, /*number*/"", /*type*/2, /*index_text*/"k.dummy", /*title*/"k.dummy", /*summary*/"k.dummy", /*member_group*/2, /*thumbnail_asset_path*/"", /*popup_thumbnail_asset_path*/"", /*scenario_script_asset_path*/"", /*movie_asset_path*/"", /*live_difficulty_id*/31001104, /*unlock_live_id*/11001, /*live_icon_asset_path*/"", /*transformation_reference_cell_id*/"");
INSERT INTO `m_story_main_cell` VALUES (/*id*/4003, /*chapter_id*/4, /*display_order*/3, /*number*/2, /*type*/1, /*index_text*/"m.story_index_title_2", /*title*/"m.story_main_title_4_2", /*summary*/"m.story_main_summary_4_2", /*member_group*/100, /*thumbnail_asset_path*/"C/I", /*popup_thumbnail_asset_path*/"}k,", /*scenario_script_asset_path*/"MS/004/ms_004_02", /*movie_asset_path*/"", /*live_difficulty_id*/"", /*unlock_live_id*/"", /*live_icon_asset_path*/"", /*transformation_reference_cell_id*/"");
INSERT INTO `m_story_main_cell` VALUES (/*id*/4004, /*chapter_id*/4, /*display_order*/4, /*number*/"", /*type*/2, /*index_text*/"k.dummy", /*title*/"k.dummy", /*summary*/"k.dummy", /*member_group*/2, /*thumbnail_asset_path*/"", /*popup_thumbnail_asset_path*/"", /*scenario_script_asset_path*/"", /*movie_asset_path*/"", /*live_difficulty_id*/31004101, /*unlock_live_id*/11004, /*live_icon_asset_path*/"", /*transformation_reference_cell_id*/"");
INSERT INTO `m_story_main_cell` VALUES (/*id*/4005, /*chapter_id*/4, /*display_order*/5, /*number*/3, /*type*/1, /*index_text*/"m.story_index_title_3", /*title*/"m.story_main_title_4_3", /*summary*/"m.story_main_summary_4_3", /*member_group*/100, /*thumbnail_asset_path*/"\LO", /*popup_thumbnail_asset_path*/"^<z", /*scenario_script_asset_path*/"MS/004/ms_004_03", /*movie_asset_path*/"", /*live_difficulty_id*/"", /*unlock_live_id*/"", /*live_icon_asset_path*/"", /*transformation_reference_cell_id*/"");
INSERT INTO `m_story_main_cell` VALUES (/*id*/4006, /*chapter_id*/4, /*display_order*/6, /*number*/"", /*type*/2, /*index_text*/"k.dummy", /*title*/"k.dummy", /*summary*/"k.dummy", /*member_group*/3, /*thumbnail_asset_path*/"", /*popup_thumbnail_asset_path*/"", /*scenario_script_asset_path*/"", /*movie_asset_path*/"", /*live_difficulty_id*/32010101, /*unlock_live_id*/12010, /*live_icon_asset_path*/"", /*transformation_reference_cell_id*/"");
INSERT INTO `m_story_main_cell` VALUES (/*id*/4007, /*chapter_id*/4, /*display_order*/7, /*number*/4, /*type*/1, /*index_text*/"m.story_index_title_4", /*title*/"m.story_main_title_4_4", /*summary*/"m.story_main_summary_4_4", /*member_group*/100, /*thumbnail_asset_path*/"A{G", /*popup_thumbnail_asset_path*/"o)B", /*scenario_script_asset_path*/"MS/004/ms_004_04", /*movie_asset_path*/"", /*live_difficulty_id*/"", /*unlock_live_id*/"", /*live_icon_asset_path*/"", /*transformation_reference_cell_id*/"");
INSERT INTO `m_story_main_cell` VALUES (/*id*/4008, /*chapter_id*/4, /*display_order*/8, /*number*/"", /*type*/2, /*index_text*/"k.dummy", /*title*/"k.dummy", /*summary*/"k.dummy", /*member_group*/3, /*thumbnail_asset_path*/"", /*popup_thumbnail_asset_path*/"", /*scenario_script_asset_path*/"", /*movie_asset_path*/"", /*live_difficulty_id*/32002201, /*unlock_live_id*/12002, /*live_icon_asset_path*/"", /*transformation_reference_cell_id*/"");
INSERT INTO `m_story_main_cell` VALUES (/*id*/4009, /*chapter_id*/4, /*display_order*/9, /*number*/5, /*type*/1, /*index_text*/"m.story_index_title_5", /*title*/"m.story_main_title_4_5", /*summary*/"m.story_main_summary_4_5", /*member_group*/100, /*thumbnail_asset_path*/"0},", /*popup_thumbnail_asset_path*/"xP3", /*scenario_script_asset_path*/"MS/004/ms_004_05", /*movie_asset_path*/"", /*live_difficulty_id*/"", /*unlock_live_id*/"", /*live_icon_asset_path*/"", /*transformation_reference_cell_id*/"");
INSERT INTO `m_story_main_cell` VALUES (/*id*/4010, /*chapter_id*/4, /*display_order*/10, /*number*/"", /*type*/2, /*index_text*/"k.dummy", /*title*/"k.dummy", /*summary*/"k.dummy", /*member_group*/2, /*thumbnail_asset_path*/"", /*popup_thumbnail_asset_path*/"", /*scenario_script_asset_path*/"", /*movie_asset_path*/"", /*live_difficulty_id*/31007103, /*unlock_live_id*/11007, /*live_icon_asset_path*/"", /*transformation_reference_cell_id*/"");
INSERT INTO `m_story_main_cell` VALUES (/*id*/4011, /*chapter_id*/4, /*display_order*/11, /*number*/"", /*type*/2, /*index_text*/"k.dummy", /*title*/"k.dummy", /*summary*/"k.dummy", /*member_group*/3, /*thumbnail_asset_path*/"", /*popup_thumbnail_asset_path*/"", /*scenario_script_asset_path*/"", /*movie_asset_path*/"", /*live_difficulty_id*/32006101, /*unlock_live_id*/12006, /*live_icon_asset_path*/"", /*transformation_reference_cell_id*/"");
INSERT INTO `m_story_main_cell` VALUES (/*id*/4012, /*chapter_id*/4, /*display_order*/12, /*number*/6, /*type*/1, /*index_text*/"m.story_index_title_6", /*title*/"m.story_main_title_4_6", /*summary*/"m.story_main_summary_4_6", /*member_group*/100, /*thumbnail_asset_path*/"Ky+", /*popup_thumbnail_asset_path*/"1eQ", /*scenario_script_asset_path*/"MS/004/ms_004_06", /*movie_asset_path*/"", /*live_difficulty_id*/"", /*unlock_live_id*/"", /*live_icon_asset_path*/"", /*transformation_reference_cell_id*/"");
INSERT INTO `m_story_main_cell` VALUES (/*id*/4013, /*chapter_id*/4, /*display_order*/13, /*number*/"", /*type*/2, /*index_text*/"k.dummy", /*title*/"k.dummy", /*summary*/"k.dummy", /*member_group*/2, /*thumbnail_asset_path*/"", /*popup_thumbnail_asset_path*/"", /*scenario_script_asset_path*/"", /*movie_asset_path*/"", /*live_difficulty_id*/31002103, /*unlock_live_id*/11002, /*live_icon_asset_path*/"", /*transformation_reference_cell_id*/"");
INSERT INTO `m_story_main_cell` VALUES (/*id*/4014, /*chapter_id*/4, /*display_order*/14, /*number*/7, /*type*/1, /*index_text*/"m.story_index_title_7", /*title*/"m.story_main_title_4_7", /*summary*/"m.story_main_summary_4_7", /*member_group*/100, /*thumbnail_asset_path*/"xz2", /*popup_thumbnail_asset_path*/"t5R", /*scenario_script_asset_path*/"MS/004/ms_004_07", /*movie_asset_path*/"", /*live_difficulty_id*/"", /*unlock_live_id*/"", /*live_icon_asset_path*/"", /*transformation_reference_cell_id*/"");
INSERT INTO `m_story_main_cell` VALUES (/*id*/4015, /*chapter_id*/4, /*display_order*/15, /*number*/"", /*type*/2, /*index_text*/"k.dummy", /*title*/"k.dummy", /*summary*/"k.dummy", /*member_group*/2, /*thumbnail_asset_path*/"", /*popup_thumbnail_asset_path*/"", /*scenario_script_asset_path*/"", /*movie_asset_path*/"", /*live_difficulty_id*/31004201, /*unlock_live_id*/11004, /*live_icon_asset_path*/"", /*transformation_reference_cell_id*/"");
INSERT INTO `m_story_main_cell` VALUES (/*id*/4016, /*chapter_id*/4, /*display_order*/16, /*number*/8, /*type*/1, /*index_text*/"m.story_index_title_8", /*title*/"m.story_main_title_4_8", /*summary*/"m.story_main_summary_4_8", /*member_group*/100, /*thumbnail_asset_path*/"9qs", /*popup_thumbnail_asset_path*/"I6)", /*scenario_script_asset_path*/"MS/004/ms_004_08", /*movie_asset_path*/"", /*live_difficulty_id*/"", /*unlock_live_id*/"", /*live_icon_asset_path*/"", /*transformation_reference_cell_id*/"");
INSERT INTO `m_story_main_cell` VALUES (/*id*/4017, /*chapter_id*/4, /*display_order*/17, /*number*/"", /*type*/2, /*index_text*/"k.dummy", /*title*/"k.dummy", /*summary*/"k.dummy", /*member_group*/2, /*thumbnail_asset_path*/"", /*popup_thumbnail_asset_path*/"", /*scenario_script_asset_path*/"", /*movie_asset_path*/"", /*live_difficulty_id*/31006101, /*unlock_live_id*/11006, /*live_icon_asset_path*/"", /*transformation_reference_cell_id*/"");
INSERT INTO `m_story_main_cell` VALUES (/*id*/4018, /*chapter_id*/4, /*display_order*/18, /*number*/"", /*type*/2, /*index_text*/"k.dummy", /*title*/"k.dummy", /*summary*/"k.dummy", /*member_group*/2, /*thumbnail_asset_path*/"", /*popup_thumbnail_asset_path*/"", /*scenario_script_asset_path*/"", /*movie_asset_path*/"", /*live_difficulty_id*/31005102, /*unlock_live_id*/11005, /*live_icon_asset_path*/"", /*transformation_reference_cell_id*/"");
INSERT INTO `m_story_main_cell` VALUES (/*id*/4019, /*chapter_id*/4, /*display_order*/19, /*number*/9, /*type*/1, /*index_text*/"m.story_index_title_9", /*title*/"m.story_main_title_4_9", /*summary*/"m.story_main_summary_4_9", /*member_group*/100, /*thumbnail_asset_path*/"x!)", /*popup_thumbnail_asset_path*/"l`q", /*scenario_script_asset_path*/"MS/004/ms_004_09", /*movie_asset_path*/"", /*live_difficulty_id*/"", /*unlock_live_id*/"", /*live_icon_asset_path*/"", /*transformation_reference_cell_id*/"");
INSERT INTO `m_story_main_cell` VALUES (/*id*/4020, /*chapter_id*/4, /*display_order*/20, /*number*/"", /*type*/4, /*index_text*/"k.dummy", /*title*/"k.dummy", /*summary*/"k.dummy", /*member_group*/2, /*thumbnail_asset_path*/"", /*popup_thumbnail_asset_path*/"", /*scenario_script_asset_path*/"", /*movie_asset_path*/"", /*live_difficulty_id*/31014301, /*unlock_live_id*/11014, /*live_icon_asset_path*/"o~+", /*transformation_reference_cell_id*/"");
INSERT INTO `m_story_main_cell` VALUES (/*id*/4021, /*chapter_id*/4, /*display_order*/21, /*number*/10, /*type*/1, /*index_text*/"m.story_index_title_10", /*title*/"m.story_main_title_4_10", /*summary*/"m.story_main_summary_4_10", /*member_group*/100, /*thumbnail_asset_path*/"CKW", /*popup_thumbnail_asset_path*/"wri", /*scenario_script_asset_path*/"MS/004/ms_004_10", /*movie_asset_path*/"", /*live_difficulty_id*/"", /*unlock_live_id*/"", /*live_icon_asset_path*/"", /*transformation_reference_cell_id*/"");
INSERT INTO `m_story_main_cell` VALUES (/*id*/5001, /*chapter_id*/5, /*display_order*/1, /*number*/1, /*type*/1, /*index_text*/"m.story_index_title_1", /*title*/"m.story_main_title_5_1", /*summary*/"m.story_main_summary_5_1", /*member_group*/100, /*thumbnail_asset_path*/"R)x", /*popup_thumbnail_asset_path*/"(/w", /*scenario_script_asset_path*/"MS/005/ms_005_01", /*movie_asset_path*/"", /*live_difficulty_id*/"", /*unlock_live_id*/"", /*live_icon_asset_path*/"", /*transformation_reference_cell_id*/"");
INSERT INTO `m_story_main_cell` VALUES (/*id*/5002, /*chapter_id*/5, /*display_order*/2, /*number*/"", /*type*/2, /*index_text*/"k.dummy", /*title*/"k.dummy", /*summary*/"k.dummy", /*member_group*/1, /*thumbnail_asset_path*/"", /*popup_thumbnail_asset_path*/"", /*scenario_script_asset_path*/"", /*movie_asset_path*/"", /*live_difficulty_id*/30001103, /*unlock_live_id*/10001, /*live_icon_asset_path*/"", /*transformation_reference_cell_id*/"");
INSERT INTO `m_story_main_cell` VALUES (/*id*/5003, /*chapter_id*/5, /*display_order*/3, /*number*/2, /*type*/1, /*index_text*/"m.story_index_title_2", /*title*/"m.story_main_title_5_2", /*summary*/"m.story_main_summary_5_2", /*member_group*/100, /*thumbnail_asset_path*/"#to", /*popup_thumbnail_asset_path*/"[/N", /*scenario_script_asset_path*/"MS/005/ms_005_02", /*movie_asset_path*/"", /*live_difficulty_id*/"", /*unlock_live_id*/"", /*live_icon_asset_path*/"", /*transformation_reference_cell_id*/"");
INSERT INTO `m_story_main_cell` VALUES (/*id*/5004, /*chapter_id*/5, /*display_order*/4, /*number*/"", /*type*/2, /*index_text*/"k.dummy", /*title*/"k.dummy", /*summary*/"k.dummy", /*member_group*/1, /*thumbnail_asset_path*/"", /*popup_thumbnail_asset_path*/"", /*scenario_script_asset_path*/"", /*movie_asset_path*/"", /*live_difficulty_id*/30015101, /*unlock_live_id*/10015, /*live_icon_asset_path*/"", /*transformation_reference_cell_id*/"");
INSERT INTO `m_story_main_cell` VALUES (/*id*/5005, /*chapter_id*/5, /*display_order*/5, /*number*/3, /*type*/1, /*index_text*/"m.story_index_title_3", /*title*/"m.story_main_title_5_3", /*summary*/"m.story_main_summary_5_3", /*member_group*/100, /*thumbnail_asset_path*/"0;;", /*popup_thumbnail_asset_path*/"xlA", /*scenario_script_asset_path*/"MS/005/ms_005_03", /*movie_asset_path*/"", /*live_difficulty_id*/"", /*unlock_live_id*/"", /*live_icon_asset_path*/"", /*transformation_reference_cell_id*/"");
INSERT INTO `m_story_main_cell` VALUES (/*id*/5006, /*chapter_id*/5, /*display_order*/6, /*number*/"", /*type*/2, /*index_text*/"k.dummy", /*title*/"k.dummy", /*summary*/"k.dummy", /*member_group*/1, /*thumbnail_asset_path*/"", /*popup_thumbnail_asset_path*/"", /*scenario_script_asset_path*/"", /*movie_asset_path*/"", /*live_difficulty_id*/30014102, /*unlock_live_id*/10014, /*live_icon_asset_path*/"", /*transformation_reference_cell_id*/"");
INSERT INTO `m_story_main_cell` VALUES (/*id*/5007, /*chapter_id*/5, /*display_order*/7, /*number*/4, /*type*/1, /*index_text*/"m.story_index_title_4", /*title*/"m.story_main_title_5_4", /*summary*/"m.story_main_summary_5_4", /*member_group*/100, /*thumbnail_asset_path*/"K7:", /*popup_thumbnail_asset_path*/"+l0", /*scenario_script_asset_path*/"MS/005/ms_005_04", /*movie_asset_path*/"", /*live_difficulty_id*/"", /*unlock_live_id*/"", /*live_icon_asset_path*/"", /*transformation_reference_cell_id*/"");
INSERT INTO `m_story_main_cell` VALUES (/*id*/5008, /*chapter_id*/5, /*display_order*/8, /*number*/"", /*type*/2, /*index_text*/"k.dummy", /*title*/"k.dummy", /*summary*/"k.dummy", /*member_group*/1, /*thumbnail_asset_path*/"", /*popup_thumbnail_asset_path*/"", /*scenario_script_asset_path*/"", /*movie_asset_path*/"", /*live_difficulty_id*/30005101, /*unlock_live_id*/10005, /*live_icon_asset_path*/"", /*transformation_reference_cell_id*/"");
INSERT INTO `m_story_main_cell` VALUES (/*id*/5009, /*chapter_id*/5, /*display_order*/9, /*number*/5, /*type*/1, /*index_text*/"m.story_index_title_5", /*title*/"m.story_main_title_5_5", /*summary*/"m.story_main_summary_5_5", /*member_group*/100, /*thumbnail_asset_path*/"ZsZ", /*popup_thumbnail_asset_path*/"`;^", /*scenario_script_asset_path*/"MS/005/ms_005_05", /*movie_asset_path*/"", /*live_difficulty_id*/"", /*unlock_live_id*/"", /*live_icon_asset_path*/"", /*transformation_reference_cell_id*/"");
INSERT INTO `m_story_main_cell` VALUES (/*id*/5010, /*chapter_id*/5, /*display_order*/10, /*number*/"", /*type*/2, /*index_text*/"k.dummy", /*title*/"k.dummy", /*summary*/"k.dummy", /*member_group*/1, /*thumbnail_asset_path*/"", /*popup_thumbnail_asset_path*/"", /*scenario_script_asset_path*/"", /*movie_asset_path*/"", /*live_difficulty_id*/30002201, /*unlock_live_id*/10002, /*live_icon_asset_path*/"", /*transformation_reference_cell_id*/"");
INSERT INTO `m_story_main_cell` VALUES (/*id*/5011, /*chapter_id*/5, /*display_order*/11, /*number*/6, /*type*/1, /*index_text*/"m.story_index_title_6", /*title*/"m.story_main_title_5_6", /*summary*/"m.story_main_summary_5_6", /*member_group*/100, /*thumbnail_asset_path*/"9/$", /*popup_thumbnail_asset_path*/"IR7", /*scenario_script_asset_path*/"MS/005/ms_005_06", /*movie_asset_path*/"", /*live_difficulty_id*/"", /*unlock_live_id*/"", /*live_icon_asset_path*/"", /*transformation_reference_cell_id*/"");
INSERT INTO `m_story_main_cell` VALUES (/*id*/5012, /*chapter_id*/5, /*display_order*/12, /*number*/"", /*type*/2, /*index_text*/"k.dummy", /*title*/"k.dummy", /*summary*/"k.dummy", /*member_group*/1, /*thumbnail_asset_path*/"", /*popup_thumbnail_asset_path*/"", /*scenario_script_asset_path*/"", /*movie_asset_path*/"", /*live_difficulty_id*/30015102, /*unlock_live_id*/10015, /*live_icon_asset_path*/"", /*transformation_reference_cell_id*/"");
INSERT INTO `m_story_main_cell` VALUES (/*id*/5013, /*chapter_id*/5, /*display_order*/13, /*number*/7, /*type*/1, /*index_text*/"m.story_index_title_7", /*title*/"m.story_main_title_5_7", /*summary*/"m.story_main_summary_5_7", /*member_group*/100, /*thumbnail_asset_path*/"hG\"", /*popup_thumbnail_asset_path*/"Ry(", /*scenario_script_asset_path*/"MS/005/ms_005_07", /*movie_asset_path*/"", /*live_difficulty_id*/"", /*unlock_live_id*/"", /*live_icon_asset_path*/"", /*transformation_reference_cell_id*/"");
INSERT INTO `m_story_main_cell` VALUES (/*id*/5014, /*chapter_id*/5, /*display_order*/14, /*number*/"", /*type*/2, /*index_text*/"k.dummy", /*title*/"k.dummy", /*summary*/"k.dummy", /*member_group*/3, /*thumbnail_asset_path*/"", /*popup_thumbnail_asset_path*/"", /*scenario_script_asset_path*/"", /*movie_asset_path*/"", /*live_difficulty_id*/32009101, /*unlock_live_id*/12009, /*live_icon_asset_path*/"", /*transformation_reference_cell_id*/"");
INSERT INTO `m_story_main_cell` VALUES (/*id*/5015, /*chapter_id*/5, /*display_order*/15, /*number*/"", /*type*/2, /*index_text*/"k.dummy", /*title*/"k.dummy", /*summary*/"k.dummy", /*member_group*/1, /*thumbnail_asset_path*/"", /*popup_thumbnail_asset_path*/"", /*scenario_script_asset_path*/"", /*movie_asset_path*/"", /*live_difficulty_id*/30014103, /*unlock_live_id*/10014, /*live_icon_asset_path*/"", /*transformation_reference_cell_id*/"");
INSERT INTO `m_story_main_cell` VALUES (/*id*/5016, /*chapter_id*/5, /*display_order*/16, /*number*/8, /*type*/1, /*index_text*/"m.story_index_title_8", /*title*/"m.story_main_title_5_8", /*summary*/"m.story_main_summary_5_8", /*member_group*/100, /*thumbnail_asset_path*/"%D!", /*popup_thumbnail_asset_path*/"cxu", /*scenario_script_asset_path*/"MS/005/ms_005_08", /*movie_asset_path*/"", /*live_difficulty_id*/"", /*unlock_live_id*/"", /*live_icon_asset_path*/"", /*transformation_reference_cell_id*/"");
INSERT INTO `m_story_main_cell` VALUES (/*id*/5017, /*chapter_id*/5, /*display_order*/17, /*number*/"", /*type*/2, /*index_text*/"k.dummy", /*title*/"k.dummy", /*summary*/"k.dummy", /*member_group*/1, /*thumbnail_asset_path*/"", /*popup_thumbnail_asset_path*/"", /*scenario_script_asset_path*/"", /*movie_asset_path*/"", /*live_difficulty_id*/30005201, /*unlock_live_id*/10005, /*live_icon_asset_path*/"", /*transformation_reference_cell_id*/"");
INSERT INTO `m_story_main_cell` VALUES (/*id*/5018, /*chapter_id*/5, /*display_order*/18, /*number*/"", /*type*/2, /*index_text*/"k.dummy", /*title*/"k.dummy", /*summary*/"k.dummy", /*member_group*/3, /*thumbnail_asset_path*/"", /*popup_thumbnail_asset_path*/"", /*scenario_script_asset_path*/"", /*movie_asset_path*/"", /*live_difficulty_id*/32005102, /*unlock_live_id*/12005, /*live_icon_asset_path*/"", /*transformation_reference_cell_id*/"");
INSERT INTO `m_story_main_cell` VALUES (/*id*/5019, /*chapter_id*/5, /*display_order*/19, /*number*/9, /*type*/1, /*index_text*/"m.story_index_title_9", /*title*/"m.story_main_title_5_9", /*summary*/"m.story_main_summary_5_9", /*member_group*/100, /*thumbnail_asset_path*/"h(4", /*popup_thumbnail_asset_path*/"$+:", /*scenario_script_asset_path*/"MS/005/ms_005_09", /*movie_asset_path*/"", /*live_difficulty_id*/"", /*unlock_live_id*/"", /*live_icon_asset_path*/"", /*transformation_reference_cell_id*/"");
INSERT INTO `m_story_main_cell` VALUES (/*id*/5020, /*chapter_id*/5, /*display_order*/20, /*number*/"", /*type*/2, /*index_text*/"k.dummy", /*title*/"k.dummy", /*summary*/"k.dummy", /*member_group*/1, /*thumbnail_asset_path*/"", /*popup_thumbnail_asset_path*/"", /*scenario_script_asset_path*/"", /*movie_asset_path*/"", /*live_difficulty_id*/30001202, /*unlock_live_id*/10001, /*live_icon_asset_path*/"", /*transformation_reference_cell_id*/"");
INSERT INTO `m_story_main_cell` VALUES (/*id*/5021, /*chapter_id*/5, /*display_order*/21, /*number*/"", /*type*/4, /*index_text*/"k.dummy", /*title*/"k.dummy", /*summary*/"k.dummy", /*member_group*/3, /*thumbnail_asset_path*/"", /*popup_thumbnail_asset_path*/"", /*scenario_script_asset_path*/"", /*movie_asset_path*/"", /*live_difficulty_id*/32004102, /*unlock_live_id*/12004, /*live_icon_asset_path*/"3RW", /*transformation_reference_cell_id*/"");
INSERT INTO `m_story_main_cell` VALUES (/*id*/5022, /*chapter_id*/5, /*display_order*/22, /*number*/10, /*type*/1, /*index_text*/"m.story_index_title_10", /*title*/"m.story_main_title_5_10", /*summary*/"m.story_main_summary_5_10", /*member_group*/100, /*thumbnail_asset_path*/"q;i", /*popup_thumbnail_asset_path*/"[K\", /*scenario_script_asset_path*/"MS/005/ms_005_10", /*movie_asset_path*/"", /*live_difficulty_id*/"", /*unlock_live_id*/"", /*live_icon_asset_path*/"", /*transformation_reference_cell_id*/"");
INSERT INTO `m_story_main_cell` VALUES (/*id*/6001, /*chapter_id*/6, /*display_order*/1, /*number*/1, /*type*/1, /*index_text*/"m.story_index_title_1", /*title*/"m.story_main_title_6_1", /*summary*/"m.story_main_summary_6_1", /*member_group*/100, /*thumbnail_asset_path*/"p3c", /*popup_thumbnail_asset_path*/"drM", /*scenario_script_asset_path*/"MS/006/ms_006_01", /*movie_asset_path*/"", /*live_difficulty_id*/"", /*unlock_live_id*/"", /*live_icon_asset_path*/"", /*transformation_reference_cell_id*/"");
INSERT INTO `m_story_main_cell` VALUES (/*id*/6002, /*chapter_id*/6, /*display_order*/2, /*number*/"", /*type*/2, /*index_text*/"k.dummy", /*title*/"k.dummy", /*summary*/"k.dummy", /*member_group*/3, /*thumbnail_asset_path*/"", /*popup_thumbnail_asset_path*/"", /*scenario_script_asset_path*/"", /*movie_asset_path*/"", /*live_difficulty_id*/32007101, /*unlock_live_id*/12007, /*live_icon_asset_path*/"", /*transformation_reference_cell_id*/"");
INSERT INTO `m_story_main_cell` VALUES (/*id*/6003, /*chapter_id*/6, /*display_order*/3, /*number*/2, /*type*/1, /*index_text*/"m.story_index_title_2", /*title*/"m.story_main_title_6_2", /*summary*/"m.story_main_summary_6_2", /*member_group*/100, /*thumbnail_asset_path*/"Q@?", /*popup_thumbnail_asset_path*/"'hQ", /*scenario_script_asset_path*/"MS/006/ms_006_02", /*movie_asset_path*/"", /*live_difficulty_id*/"", /*unlock_live_id*/"", /*live_icon_asset_path*/"", /*transformation_reference_cell_id*/"");
INSERT INTO `m_story_main_cell` VALUES (/*id*/6004, /*chapter_id*/6, /*display_order*/4, /*number*/"", /*type*/2, /*index_text*/"k.dummy", /*title*/"k.dummy", /*summary*/"k.dummy", /*member_group*/3, /*thumbnail_asset_path*/"", /*popup_thumbnail_asset_path*/"", /*scenario_script_asset_path*/"", /*movie_asset_path*/"", /*live_difficulty_id*/32006201, /*unlock_live_id*/12006, /*live_icon_asset_path*/"", /*transformation_reference_cell_id*/"");
INSERT INTO `m_story_main_cell` VALUES (/*id*/6005, /*chapter_id*/6, /*display_order*/5, /*number*/"", /*type*/2, /*index_text*/"k.dummy", /*title*/"k.dummy", /*summary*/"k.dummy", /*member_group*/1, /*thumbnail_asset_path*/"", /*popup_thumbnail_asset_path*/"", /*scenario_script_asset_path*/"", /*movie_asset_path*/"", /*live_difficulty_id*/30014104, /*unlock_live_id*/10014, /*live_icon_asset_path*/"", /*transformation_reference_cell_id*/"");
INSERT INTO `m_story_main_cell` VALUES (/*id*/6006, /*chapter_id*/6, /*display_order*/6, /*number*/3, /*type*/1, /*index_text*/"m.story_index_title_3", /*title*/"m.story_main_title_6_3", /*summary*/"m.story_main_summary_6_3", /*member_group*/100, /*thumbnail_asset_path*/"Z1i", /*popup_thumbnail_asset_path*/"`Wl", /*scenario_script_asset_path*/"MS/006/ms_006_03", /*movie_asset_path*/"", /*live_difficulty_id*/"", /*unlock_live_id*/"", /*live_icon_asset_path*/"", /*transformation_reference_cell_id*/"");
INSERT INTO `m_story_main_cell` VALUES (/*id*/6007, /*chapter_id*/6, /*display_order*/7, /*number*/"", /*type*/2, /*index_text*/"k.dummy", /*title*/"k.dummy", /*summary*/"k.dummy", /*member_group*/3, /*thumbnail_asset_path*/"", /*popup_thumbnail_asset_path*/"", /*scenario_script_asset_path*/"", /*movie_asset_path*/"", /*live_difficulty_id*/32008201, /*unlock_live_id*/12008, /*live_icon_asset_path*/"", /*transformation_reference_cell_id*/"");
INSERT INTO `m_story_main_cell` VALUES (/*id*/6008, /*chapter_id*/6, /*display_order*/8, /*number*/"", /*type*/2, /*index_text*/"k.dummy", /*title*/"k.dummy", /*summary*/"k.dummy", /*member_group*/1, /*thumbnail_asset_path*/"", /*popup_thumbnail_asset_path*/"", /*scenario_script_asset_path*/"", /*movie_asset_path*/"", /*live_difficulty_id*/30004101, /*unlock_live_id*/10004, /*live_icon_asset_path*/"", /*transformation_reference_cell_id*/"");
INSERT INTO `m_story_main_cell` VALUES (/*id*/6009, /*chapter_id*/6, /*display_order*/9, /*number*/4, /*type*/1, /*index_text*/"m.story_index_title_4", /*title*/"m.story_main_title_6_4", /*summary*/"m.story_main_summary_6_4", /*member_group*/100, /*thumbnail_asset_path*/"QQ]", /*popup_thumbnail_asset_path*/"5XC", /*scenario_script_asset_path*/"MS/006/ms_006_04", /*movie_asset_path*/"", /*live_difficulty_id*/"", /*unlock_live_id*/"", /*live_icon_asset_path*/"", /*transformation_reference_cell_id*/"");
INSERT INTO `m_story_main_cell` VALUES (/*id*/6010, /*chapter_id*/6, /*display_order*/10, /*number*/"", /*type*/2, /*index_text*/"k.dummy", /*title*/"k.dummy", /*summary*/"k.dummy", /*member_group*/1, /*thumbnail_asset_path*/"", /*popup_thumbnail_asset_path*/"", /*scenario_script_asset_path*/"", /*movie_asset_path*/"", /*live_difficulty_id*/30002102, /*unlock_live_id*/10002, /*live_icon_asset_path*/"", /*transformation_reference_cell_id*/"");
INSERT INTO `m_story_main_cell` VALUES (/*id*/6011, /*chapter_id*/6, /*display_order*/11, /*number*/"", /*type*/2, /*index_text*/"k.dummy", /*title*/"k.dummy", /*summary*/"k.dummy", /*member_group*/3, /*thumbnail_asset_path*/"", /*popup_thumbnail_asset_path*/"", /*scenario_script_asset_path*/"", /*movie_asset_path*/"", /*live_difficulty_id*/32010201, /*unlock_live_id*/12010, /*live_icon_asset_path*/"", /*transformation_reference_cell_id*/"");
INSERT INTO `m_story_main_cell` VALUES (/*id*/6012, /*chapter_id*/6, /*display_order*/12, /*number*/5, /*type*/1, /*index_text*/"m.story_index_title_5", /*title*/"m.story_main_title_6_5", /*summary*/"m.story_main_summary_6_5", /*member_group*/100, /*thumbnail_asset_path*/"~F<", /*popup_thumbnail_asset_path*/"hxB", /*scenario_script_asset_path*/"MS/006/ms_006_05", /*movie_asset_path*/"", /*live_difficulty_id*/"", /*unlock_live_id*/"", /*live_icon_asset_path*/"", /*transformation_reference_cell_id*/"");
INSERT INTO `m_story_main_cell` VALUES (/*id*/6013, /*chapter_id*/6, /*display_order*/13, /*number*/"", /*type*/2, /*index_text*/"k.dummy", /*title*/"k.dummy", /*summary*/"k.dummy", /*member_group*/1, /*thumbnail_asset_path*/"", /*popup_thumbnail_asset_path*/"", /*scenario_script_asset_path*/"", /*movie_asset_path*/"", /*live_difficulty_id*/30015103, /*unlock_live_id*/10015, /*live_icon_asset_path*/"", /*transformation_reference_cell_id*/"");
INSERT INTO `m_story_main_cell` VALUES (/*id*/6014, /*chapter_id*/6, /*display_order*/14, /*number*/"", /*type*/2, /*index_text*/"k.dummy", /*title*/"k.dummy", /*summary*/"k.dummy", /*member_group*/3, /*thumbnail_asset_path*/"", /*popup_thumbnail_asset_path*/"", /*scenario_script_asset_path*/"", /*movie_asset_path*/"", /*live_difficulty_id*/32002101, /*unlock_live_id*/12002, /*live_icon_asset_path*/"", /*transformation_reference_cell_id*/"");
INSERT INTO `m_story_main_cell` VALUES (/*id*/6015, /*chapter_id*/6, /*display_order*/15, /*number*/6, /*type*/1, /*index_text*/"m.story_index_title_6", /*title*/"m.story_main_title_6_6", /*summary*/"m.story_main_summary_6_6", /*member_group*/100, /*thumbnail_asset_path*/"M6|", /*popup_thumbnail_asset_path*/"c6&", /*scenario_script_asset_path*/"MS/006/ms_006_06", /*movie_asset_path*/"", /*live_difficulty_id*/"", /*unlock_live_id*/"", /*live_icon_asset_path*/"", /*transformation_reference_cell_id*/"");
INSERT INTO `m_story_main_cell` VALUES (/*id*/6016, /*chapter_id*/6, /*display_order*/16, /*number*/"", /*type*/2, /*index_text*/"k.dummy", /*title*/"k.dummy", /*summary*/"k.dummy", /*member_group*/3, /*thumbnail_asset_path*/"", /*popup_thumbnail_asset_path*/"", /*scenario_script_asset_path*/"", /*movie_asset_path*/"", /*live_difficulty_id*/32003201, /*unlock_live_id*/12003, /*live_icon_asset_path*/"", /*transformation_reference_cell_id*/"");
INSERT INTO `m_story_main_cell` VALUES (/*id*/6017, /*chapter_id*/6, /*display_order*/17, /*number*/"", /*type*/2, /*index_text*/"k.dummy", /*title*/"k.dummy", /*summary*/"k.dummy", /*member_group*/1, /*thumbnail_asset_path*/"", /*popup_thumbnail_asset_path*/"", /*scenario_script_asset_path*/"", /*movie_asset_path*/"", /*live_difficulty_id*/30005102, /*unlock_live_id*/10005, /*live_icon_asset_path*/"", /*transformation_reference_cell_id*/"");
INSERT INTO `m_story_main_cell` VALUES (/*id*/6018, /*chapter_id*/6, /*display_order*/18, /*number*/7, /*type*/1, /*index_text*/"m.story_index_title_7", /*title*/"m.story_main_title_6_7", /*summary*/"m.story_main_summary_6_7", /*member_group*/100, /*thumbnail_asset_path*/"4>P", /*popup_thumbnail_asset_path*/"XM:", /*scenario_script_asset_path*/"MS/006/ms_006_07", /*movie_asset_path*/"", /*live_difficulty_id*/"", /*unlock_live_id*/"", /*live_icon_asset_path*/"", /*transformation_reference_cell_id*/"");
INSERT INTO `m_story_main_cell` VALUES (/*id*/6019, /*chapter_id*/6, /*display_order*/19, /*number*/"", /*type*/2, /*index_text*/"k.dummy", /*title*/"k.dummy", /*summary*/"k.dummy", /*member_group*/1, /*thumbnail_asset_path*/"", /*popup_thumbnail_asset_path*/"", /*scenario_script_asset_path*/"", /*movie_asset_path*/"", /*live_difficulty_id*/30004201, /*unlock_live_id*/10004, /*live_icon_asset_path*/"", /*transformation_reference_cell_id*/"");
INSERT INTO `m_story_main_cell` VALUES (/*id*/6020, /*chapter_id*/6, /*display_order*/20, /*number*/8, /*type*/1, /*index_text*/"m.story_index_title_8", /*title*/"m.story_main_title_6_8", /*summary*/"m.story_main_summary_6_8", /*member_group*/100, /*thumbnail_asset_path*/"_d6", /*popup_thumbnail_asset_path*/"!|k", /*scenario_script_asset_path*/"MS/006/ms_006_08", /*movie_asset_path*/"", /*live_difficulty_id*/"", /*unlock_live_id*/"", /*live_icon_asset_path*/"", /*transformation_reference_cell_id*/"");
INSERT INTO `m_story_main_cell` VALUES (/*id*/6021, /*chapter_id*/6, /*display_order*/21, /*number*/"", /*type*/2, /*index_text*/"k.dummy", /*title*/"k.dummy", /*summary*/"k.dummy", /*member_group*/1, /*thumbnail_asset_path*/"", /*popup_thumbnail_asset_path*/"", /*scenario_script_asset_path*/"", /*movie_asset_path*/"", /*live_difficulty_id*/30002103, /*unlock_live_id*/10002, /*live_icon_asset_path*/"", /*transformation_reference_cell_id*/"");
INSERT INTO `m_story_main_cell` VALUES (/*id*/6022, /*chapter_id*/6, /*display_order*/22, /*number*/"", /*type*/2, /*index_text*/"k.dummy", /*title*/"k.dummy", /*summary*/"k.dummy", /*member_group*/1, /*thumbnail_asset_path*/"", /*popup_thumbnail_asset_path*/"", /*scenario_script_asset_path*/"", /*movie_asset_path*/"", /*live_difficulty_id*/30014201, /*unlock_live_id*/10014, /*live_icon_asset_path*/"", /*transformation_reference_cell_id*/"");
INSERT INTO `m_story_main_cell` VALUES (/*id*/6023, /*chapter_id*/6, /*display_order*/23, /*number*/9, /*type*/1, /*index_text*/"m.story_index_title_9", /*title*/"m.story_main_title_6_9", /*summary*/"m.story_main_summary_6_9", /*member_group*/100, /*thumbnail_asset_path*/"pOq", /*popup_thumbnail_asset_path*/"wOo", /*scenario_script_asset_path*/"MS/006/ms_006_09", /*movie_asset_path*/"", /*live_difficulty_id*/"", /*unlock_live_id*/"", /*live_icon_asset_path*/"", /*transformation_reference_cell_id*/"");
INSERT INTO `m_story_main_cell` VALUES (/*id*/6024, /*chapter_id*/6, /*display_order*/24, /*number*/"", /*type*/4, /*index_text*/"k.dummy", /*title*/"k.dummy", /*summary*/"k.dummy", /*member_group*/1, /*thumbnail_asset_path*/"", /*popup_thumbnail_asset_path*/"", /*scenario_script_asset_path*/"", /*movie_asset_path*/"", /*live_difficulty_id*/30011301, /*unlock_live_id*/10011, /*live_icon_asset_path*/"Mt>", /*transformation_reference_cell_id*/"");
INSERT INTO `m_story_main_cell` VALUES (/*id*/6025, /*chapter_id*/6, /*display_order*/25, /*number*/10, /*type*/1, /*index_text*/"m.story_index_title_10", /*title*/"m.story_main_title_6_10", /*summary*/"m.story_main_summary_6_10", /*member_group*/100, /*thumbnail_asset_path*/"E,J", /*popup_thumbnail_asset_path*/"[,R", /*scenario_script_asset_path*/"MS/006/ms_006_10", /*movie_asset_path*/"", /*live_difficulty_id*/"", /*unlock_live_id*/"", /*live_icon_asset_path*/"", /*transformation_reference_cell_id*/"");
INSERT INTO `m_story_main_cell` VALUES (/*id*/7001, /*chapter_id*/7, /*display_order*/1, /*number*/1, /*type*/1, /*index_text*/"m.story_index_title_1", /*title*/"m.story_main_title_7_1", /*summary*/"m.story_main_summary_7_1", /*member_group*/100, /*thumbnail_asset_path*/"`:n", /*popup_thumbnail_asset_path*/"\S/", /*scenario_script_asset_path*/"MS/007/ms_007_01", /*movie_asset_path*/"", /*live_difficulty_id*/"", /*unlock_live_id*/"", /*live_icon_asset_path*/"", /*transformation_reference_cell_id*/"");
INSERT INTO `m_story_main_cell` VALUES (/*id*/7002, /*chapter_id*/7, /*display_order*/2, /*number*/"", /*type*/2, /*index_text*/"k.dummy", /*title*/"k.dummy", /*summary*/"k.dummy", /*member_group*/2, /*thumbnail_asset_path*/"", /*popup_thumbnail_asset_path*/"", /*scenario_script_asset_path*/"", /*movie_asset_path*/"", /*live_difficulty_id*/31001202, /*unlock_live_id*/11001, /*live_icon_asset_path*/"", /*transformation_reference_cell_id*/"");
INSERT INTO `m_story_main_cell` VALUES (/*id*/7003, /*chapter_id*/7, /*display_order*/3, /*number*/"", /*type*/2, /*index_text*/"k.dummy", /*title*/"k.dummy", /*summary*/"k.dummy", /*member_group*/3, /*thumbnail_asset_path*/"", /*popup_thumbnail_asset_path*/"", /*scenario_script_asset_path*/"", /*movie_asset_path*/"", /*live_difficulty_id*/32003202, /*unlock_live_id*/12003, /*live_icon_asset_path*/"", /*transformation_reference_cell_id*/"");
INSERT INTO `m_story_main_cell` VALUES (/*id*/7004, /*chapter_id*/7, /*display_order*/4, /*number*/2, /*type*/1, /*index_text*/"m.story_index_title_2", /*title*/"m.story_main_title_7_2", /*summary*/"m.story_main_summary_7_2", /*member_group*/100, /*thumbnail_asset_path*/"W$=", /*popup_thumbnail_asset_path*/"]J@", /*scenario_script_asset_path*/"MS/007/ms_007_02", /*movie_asset_path*/"", /*live_difficulty_id*/"", /*unlock_live_id*/"", /*live_icon_asset_path*/"", /*transformation_reference_cell_id*/"");
INSERT INTO `m_story_main_cell` VALUES (/*id*/7005, /*chapter_id*/7, /*display_order*/5, /*number*/"", /*type*/2, /*index_text*/"k.dummy", /*title*/"k.dummy", /*summary*/"k.dummy", /*member_group*/2, /*thumbnail_asset_path*/"", /*popup_thumbnail_asset_path*/"", /*scenario_script_asset_path*/"", /*movie_asset_path*/"", /*live_difficulty_id*/31006202, /*unlock_live_id*/11006, /*live_icon_asset_path*/"", /*transformation_reference_cell_id*/"");
INSERT INTO `m_story_main_cell` VALUES (/*id*/7006, /*chapter_id*/7, /*display_order*/6, /*number*/"", /*type*/2, /*index_text*/"k.dummy", /*title*/"k.dummy", /*summary*/"k.dummy", /*member_group*/3, /*thumbnail_asset_path*/"", /*popup_thumbnail_asset_path*/"", /*scenario_script_asset_path*/"", /*movie_asset_path*/"", /*live_difficulty_id*/32010202, /*unlock_live_id*/12010, /*live_icon_asset_path*/"", /*transformation_reference_cell_id*/"");
INSERT INTO `m_story_main_cell` VALUES (/*id*/7007, /*chapter_id*/7, /*display_order*/7, /*number*/3, /*type*/1, /*index_text*/"m.story_index_title_3", /*title*/"m.story_main_title_7_3", /*summary*/"m.story_main_summary_7_3", /*member_group*/100, /*thumbnail_asset_path*/"J\X", /*popup_thumbnail_asset_path*/"Ezl", /*scenario_script_asset_path*/"MS/007/ms_007_03", /*movie_asset_path*/"", /*live_difficulty_id*/"", /*unlock_live_id*/"", /*live_icon_asset_path*/"", /*transformation_reference_cell_id*/"");
INSERT INTO `m_story_main_cell` VALUES (/*id*/7008, /*chapter_id*/7, /*display_order*/8, /*number*/"", /*type*/2, /*index_text*/"k.dummy", /*title*/"k.dummy", /*summary*/"k.dummy", /*member_group*/1, /*thumbnail_asset_path*/"", /*popup_thumbnail_asset_path*/"", /*scenario_script_asset_path*/"", /*movie_asset_path*/"", /*live_difficulty_id*/30004202, /*unlock_live_id*/10004, /*live_icon_asset_path*/"", /*transformation_reference_cell_id*/"");
INSERT INTO `m_story_main_cell` VALUES (/*id*/7009, /*chapter_id*/7, /*display_order*/9, /*number*/"", /*type*/2, /*index_text*/"k.dummy", /*title*/"k.dummy", /*summary*/"k.dummy", /*member_group*/3, /*thumbnail_asset_path*/"", /*popup_thumbnail_asset_path*/"", /*scenario_script_asset_path*/"", /*movie_asset_path*/"", /*live_difficulty_id*/32004201, /*unlock_live_id*/12004, /*live_icon_asset_path*/"", /*transformation_reference_cell_id*/"");
INSERT INTO `m_story_main_cell` VALUES (/*id*/7010, /*chapter_id*/7, /*display_order*/10, /*number*/4, /*type*/1, /*index_text*/"m.story_index_title_4", /*title*/"m.story_main_title_7_4", /*summary*/"m.story_main_summary_7_4", /*member_group*/100, /*thumbnail_asset_path*/"S?#", /*popup_thumbnail_asset_path*/"7\X", /*scenario_script_asset_path*/"MS/007/ms_007_04", /*movie_asset_path*/"", /*live_difficulty_id*/"", /*unlock_live_id*/"", /*live_icon_asset_path*/"", /*transformation_reference_cell_id*/"");
INSERT INTO `m_story_main_cell` VALUES (/*id*/7011, /*chapter_id*/7, /*display_order*/11, /*number*/"", /*type*/2, /*index_text*/"k.dummy", /*title*/"k.dummy", /*summary*/"k.dummy", /*member_group*/2, /*thumbnail_asset_path*/"", /*popup_thumbnail_asset_path*/"", /*scenario_script_asset_path*/"", /*movie_asset_path*/"", /*live_difficulty_id*/31005201, /*unlock_live_id*/11005, /*live_icon_asset_path*/"", /*transformation_reference_cell_id*/"");
INSERT INTO `m_story_main_cell` VALUES (/*id*/7012, /*chapter_id*/7, /*display_order*/12, /*number*/"", /*type*/2, /*index_text*/"k.dummy", /*title*/"k.dummy", /*summary*/"k.dummy", /*member_group*/3, /*thumbnail_asset_path*/"", /*popup_thumbnail_asset_path*/"", /*scenario_script_asset_path*/"", /*movie_asset_path*/"", /*live_difficulty_id*/32009201, /*unlock_live_id*/12009, /*live_icon_asset_path*/"", /*transformation_reference_cell_id*/"");
INSERT INTO `m_story_main_cell` VALUES (/*id*/7013, /*chapter_id*/7, /*display_order*/13, /*number*/5, /*type*/1, /*index_text*/"m.story_index_title_5", /*title*/"m.story_main_title_7_5", /*summary*/"m.story_main_summary_7_5", /*member_group*/100, /*thumbnail_asset_path*/"J=j", /*popup_thumbnail_asset_path*/"nLT", /*scenario_script_asset_path*/"MS/007/ms_007_05", /*movie_asset_path*/"", /*live_difficulty_id*/"", /*unlock_live_id*/"", /*live_icon_asset_path*/"", /*transformation_reference_cell_id*/"");
INSERT INTO `m_story_main_cell` VALUES (/*id*/7014, /*chapter_id*/7, /*display_order*/14, /*number*/"", /*type*/2, /*index_text*/"k.dummy", /*title*/"k.dummy", /*summary*/"k.dummy", /*member_group*/1, /*thumbnail_asset_path*/"", /*popup_thumbnail_asset_path*/"", /*scenario_script_asset_path*/"", /*movie_asset_path*/"", /*live_difficulty_id*/30015201, /*unlock_live_id*/10015, /*live_icon_asset_path*/"", /*transformation_reference_cell_id*/"");
INSERT INTO `m_story_main_cell` VALUES (/*id*/7015, /*chapter_id*/7, /*display_order*/15, /*number*/"", /*type*/2, /*index_text*/"k.dummy", /*title*/"k.dummy", /*summary*/"k.dummy", /*member_group*/3, /*thumbnail_asset_path*/"", /*popup_thumbnail_asset_path*/"", /*scenario_script_asset_path*/"", /*movie_asset_path*/"", /*live_difficulty_id*/32007201, /*unlock_live_id*/12007, /*live_icon_asset_path*/"", /*transformation_reference_cell_id*/"");
INSERT INTO `m_story_main_cell` VALUES (/*id*/7016, /*chapter_id*/7, /*display_order*/16, /*number*/6, /*type*/1, /*index_text*/"m.story_index_title_6", /*title*/"m.story_main_title_7_6", /*summary*/"m.story_main_summary_7_6", /*member_group*/100, /*thumbnail_asset_path*/"11$", /*popup_thumbnail_asset_path*/"U@l", /*scenario_script_asset_path*/"MS/007/ms_007_06", /*movie_asset_path*/"", /*live_difficulty_id*/"", /*unlock_live_id*/"", /*live_icon_asset_path*/"", /*transformation_reference_cell_id*/"");
INSERT INTO `m_story_main_cell` VALUES (/*id*/7017, /*chapter_id*/7, /*display_order*/17, /*number*/"", /*type*/2, /*index_text*/"k.dummy", /*title*/"k.dummy", /*summary*/"k.dummy", /*member_group*/2, /*thumbnail_asset_path*/"", /*popup_thumbnail_asset_path*/"", /*scenario_script_asset_path*/"", /*movie_asset_path*/"", /*live_difficulty_id*/31004202, /*unlock_live_id*/11004, /*live_icon_asset_path*/"", /*transformation_reference_cell_id*/"");
INSERT INTO `m_story_main_cell` VALUES (/*id*/7018, /*chapter_id*/7, /*display_order*/18, /*number*/"", /*type*/2, /*index_text*/"k.dummy", /*title*/"k.dummy", /*summary*/"k.dummy", /*member_group*/3, /*thumbnail_asset_path*/"", /*popup_thumbnail_asset_path*/"", /*scenario_script_asset_path*/"", /*movie_asset_path*/"", /*live_difficulty_id*/32005201, /*unlock_live_id*/12005, /*live_icon_asset_path*/"", /*transformation_reference_cell_id*/"");
INSERT INTO `m_story_main_cell` VALUES (/*id*/7019, /*chapter_id*/7, /*display_order*/19, /*number*/7, /*type*/1, /*index_text*/"m.story_index_title_7", /*title*/"m.story_main_title_7_7", /*summary*/"m.story_main_summary_7_7", /*member_group*/100, /*thumbnail_asset_path*/"vXv", /*popup_thumbnail_asset_path*/"qFj", /*scenario_script_asset_path*/"MS/007/ms_007_07", /*movie_asset_path*/"", /*live_difficulty_id*/"", /*unlock_live_id*/"", /*live_icon_asset_path*/"", /*transformation_reference_cell_id*/"");
INSERT INTO `m_story_main_cell` VALUES (/*id*/7020, /*chapter_id*/7, /*display_order*/20, /*number*/"", /*type*/2, /*index_text*/"k.dummy", /*title*/"k.dummy", /*summary*/"k.dummy", /*member_group*/1, /*thumbnail_asset_path*/"", /*popup_thumbnail_asset_path*/"", /*scenario_script_asset_path*/"", /*movie_asset_path*/"", /*live_difficulty_id*/30005202, /*unlock_live_id*/10005, /*live_icon_asset_path*/"", /*transformation_reference_cell_id*/"");
INSERT INTO `m_story_main_cell` VALUES (/*id*/7021, /*chapter_id*/7, /*display_order*/21, /*number*/"", /*type*/2, /*index_text*/"k.dummy", /*title*/"k.dummy", /*summary*/"k.dummy", /*member_group*/3, /*thumbnail_asset_path*/"", /*popup_thumbnail_asset_path*/"", /*scenario_script_asset_path*/"", /*movie_asset_path*/"", /*live_difficulty_id*/32008202, /*unlock_live_id*/12008, /*live_icon_asset_path*/"", /*transformation_reference_cell_id*/"");
INSERT INTO `m_story_main_cell` VALUES (/*id*/7022, /*chapter_id*/7, /*display_order*/22, /*number*/8, /*type*/1, /*index_text*/"m.story_index_title_8", /*title*/"m.story_main_title_7_8", /*summary*/"m.story_main_summary_7_8", /*member_group*/100, /*thumbnail_asset_path*/"[+d", /*popup_thumbnail_asset_path*/"IU}", /*scenario_script_asset_path*/"MS/007/ms_007_08", /*movie_asset_path*/"", /*live_difficulty_id*/"", /*unlock_live_id*/"", /*live_icon_asset_path*/"", /*transformation_reference_cell_id*/"");
INSERT INTO `m_story_main_cell` VALUES (/*id*/7023, /*chapter_id*/7, /*display_order*/23, /*number*/"", /*type*/2, /*index_text*/"k.dummy", /*title*/"k.dummy", /*summary*/"k.dummy", /*member_group*/2, /*thumbnail_asset_path*/"", /*popup_thumbnail_asset_path*/"", /*scenario_script_asset_path*/"", /*movie_asset_path*/"", /*live_difficulty_id*/31014201, /*unlock_live_id*/11014, /*live_icon_asset_path*/"", /*transformation_reference_cell_id*/"");
INSERT INTO `m_story_main_cell` VALUES (/*id*/7024, /*chapter_id*/7, /*display_order*/24, /*number*/"", /*type*/2, /*index_text*/"k.dummy", /*title*/"k.dummy", /*summary*/"k.dummy", /*member_group*/1, /*thumbnail_asset_path*/"", /*popup_thumbnail_asset_path*/"", /*scenario_script_asset_path*/"", /*movie_asset_path*/"", /*live_difficulty_id*/30002202, /*unlock_live_id*/10002, /*live_icon_asset_path*/"", /*transformation_reference_cell_id*/"");
INSERT INTO `m_story_main_cell` VALUES (/*id*/7025, /*chapter_id*/7, /*display_order*/25, /*number*/"", /*type*/2, /*index_text*/"k.dummy", /*title*/"k.dummy", /*summary*/"k.dummy", /*member_group*/3, /*thumbnail_asset_path*/"", /*popup_thumbnail_asset_path*/"", /*scenario_script_asset_path*/"", /*movie_asset_path*/"", /*live_difficulty_id*/32006202, /*unlock_live_id*/12006, /*live_icon_asset_path*/"", /*transformation_reference_cell_id*/"");
INSERT INTO `m_story_main_cell` VALUES (/*id*/7026, /*chapter_id*/7, /*display_order*/26, /*number*/9, /*type*/1, /*index_text*/"m.story_index_title_9", /*title*/"m.story_main_title_7_9", /*summary*/"m.story_main_summary_7_9", /*member_group*/100, /*thumbnail_asset_path*/",P,", /*popup_thumbnail_asset_path*/",a^", /*scenario_script_asset_path*/"MS/007/ms_007_09", /*movie_asset_path*/"", /*live_difficulty_id*/"", /*unlock_live_id*/"", /*live_icon_asset_path*/"", /*transformation_reference_cell_id*/"");
INSERT INTO `m_story_main_cell` VALUES (/*id*/7027, /*chapter_id*/7, /*display_order*/27, /*number*/"", /*type*/2, /*index_text*/"k.dummy", /*title*/"k.dummy", /*summary*/"k.dummy", /*member_group*/3, /*thumbnail_asset_path*/"", /*popup_thumbnail_asset_path*/"", /*scenario_script_asset_path*/"", /*movie_asset_path*/"", /*live_difficulty_id*/32002202, /*unlock_live_id*/12002, /*live_icon_asset_path*/"", /*transformation_reference_cell_id*/"");
INSERT INTO `m_story_main_cell` VALUES (/*id*/7028, /*chapter_id*/7, /*display_order*/28, /*number*/10, /*type*/1, /*index_text*/"m.story_index_title_10a", /*title*/"m.story_main_title_7_10a", /*summary*/"m.story_main_summary_7_10a", /*member_group*/100, /*thumbnail_asset_path*/"]-B", /*popup_thumbnail_asset_path*/"Q/W", /*scenario_script_asset_path*/"MS/007/ms_007_10a", /*movie_asset_path*/"", /*live_difficulty_id*/"", /*unlock_live_id*/"", /*live_icon_asset_path*/"", /*transformation_reference_cell_id*/"");
INSERT INTO `m_story_main_cell` VALUES (/*id*/7029, /*chapter_id*/7, /*display_order*/29, /*number*/"", /*type*/4, /*index_text*/"k.dummy", /*title*/"k.dummy", /*summary*/"k.dummy", /*member_group*/3, /*thumbnail_asset_path*/"", /*popup_thumbnail_asset_path*/"", /*scenario_script_asset_path*/"", /*movie_asset_path*/"", /*live_difficulty_id*/32001301, /*unlock_live_id*/12001, /*live_icon_asset_path*/"3RW", /*transformation_reference_cell_id*/"");
INSERT INTO `m_story_main_cell` VALUES (/*id*/7030, /*chapter_id*/7, /*display_order*/30, /*number*/10, /*type*/1, /*index_text*/"m.story_index_title_10b", /*title*/"m.story_main_title_7_10b", /*summary*/"m.story_main_summary_7_10b", /*member_group*/100, /*thumbnail_asset_path*/"8'&", /*popup_thumbnail_asset_path*/",%w", /*scenario_script_asset_path*/"MS/007/ms_007_10b", /*movie_asset_path*/"", /*live_difficulty_id*/"", /*unlock_live_id*/"", /*live_icon_asset_path*/"", /*transformation_reference_cell_id*/"");
