CREATE TABLE m_training_material(
  id INTEGER NOT NULL,
  name TEXT NOT NULL,
  description TEXT NOT NULL,
  rarity INTEGER NOT NULL,
  image_asset_path TEXT NOT NULL,
  thumbnail_asset_path TEXT NOT NULL,
  item_list_category_type INTEGER NOT NULL,
  scene_id INTEGER NOT NULL,
  banner_image_asset_path TEXT,
  display_order INTEGER NOT NULL,
  PRIMARY KEY (id)
);
INSERT INTO `m_training_material` VALUES (/*id*/1700, /*name*/"k.item_name_1700", /*description*/"k.item_desc_1700", /*rarity*/1, /*image_asset_path*/"1F", /*thumbnail_asset_path*/"1F", /*item_list_category_type*/14, /*scene_id*/32, /*banner_image_asset_path*/"", /*display_order*/1);
INSERT INTO `m_training_material` VALUES (/*id*/1900, /*name*/"k.item_name_1900", /*description*/"k.item_desc_1900", /*rarity*/1, /*image_asset_path*/"Y#", /*thumbnail_asset_path*/"Y#", /*item_list_category_type*/8, /*scene_id*/32, /*banner_image_asset_path*/"", /*display_order*/4);
INSERT INTO `m_training_material` VALUES (/*id*/1901, /*name*/"k.item_name_1901", /*description*/"k.item_desc_1900", /*rarity*/2, /*image_asset_path*/"7J", /*thumbnail_asset_path*/"7J", /*item_list_category_type*/8, /*scene_id*/32, /*banner_image_asset_path*/"", /*display_order*/5);
INSERT INTO `m_training_material` VALUES (/*id*/1902, /*name*/"k.item_name_1902", /*description*/"k.item_desc_1900", /*rarity*/3, /*image_asset_path*/"vI", /*thumbnail_asset_path*/"vI", /*item_list_category_type*/8, /*scene_id*/32, /*banner_image_asset_path*/"", /*display_order*/6);
INSERT INTO `m_training_material` VALUES (/*id*/1910, /*name*/"k.item_name_1910", /*description*/"k.item_desc_1900", /*rarity*/1, /*image_asset_path*/">E", /*thumbnail_asset_path*/">E", /*item_list_category_type*/8, /*scene_id*/32, /*banner_image_asset_path*/"", /*display_order*/7);
INSERT INTO `m_training_material` VALUES (/*id*/1911, /*name*/"k.item_name_1911", /*description*/"k.item_desc_1900", /*rarity*/2, /*image_asset_path*/"G.", /*thumbnail_asset_path*/"G.", /*item_list_category_type*/8, /*scene_id*/32, /*banner_image_asset_path*/"", /*display_order*/8);
INSERT INTO `m_training_material` VALUES (/*id*/1912, /*name*/"k.item_name_1912", /*description*/"k.item_desc_1900", /*rarity*/3, /*image_asset_path*/"\]", /*thumbnail_asset_path*/"\]", /*item_list_category_type*/8, /*scene_id*/32, /*banner_image_asset_path*/"", /*display_order*/9);
INSERT INTO `m_training_material` VALUES (/*id*/1920, /*name*/"k.item_name_1920", /*description*/"k.item_desc_1900", /*rarity*/1, /*image_asset_path*/";!", /*thumbnail_asset_path*/";!", /*item_list_category_type*/8, /*scene_id*/32, /*banner_image_asset_path*/"", /*display_order*/10);
INSERT INTO `m_training_material` VALUES (/*id*/1921, /*name*/"k.item_name_1921", /*description*/"k.item_desc_1900", /*rarity*/2, /*image_asset_path*/"1,", /*thumbnail_asset_path*/"1,", /*item_list_category_type*/8, /*scene_id*/32, /*banner_image_asset_path*/"", /*display_order*/11);
INSERT INTO `m_training_material` VALUES (/*id*/1922, /*name*/"k.item_name_1922", /*description*/"k.item_desc_1900", /*rarity*/3, /*image_asset_path*/"7&", /*thumbnail_asset_path*/"7&", /*item_list_category_type*/8, /*scene_id*/32, /*banner_image_asset_path*/"", /*display_order*/12);
INSERT INTO `m_training_material` VALUES (/*id*/1930, /*name*/"k.item_name_1930", /*description*/"k.item_desc_1900", /*rarity*/1, /*image_asset_path*/"Ww", /*thumbnail_asset_path*/"Ww", /*item_list_category_type*/8, /*scene_id*/32, /*banner_image_asset_path*/"", /*display_order*/13);
INSERT INTO `m_training_material` VALUES (/*id*/1931, /*name*/"k.item_name_1931", /*description*/"k.item_desc_1900", /*rarity*/2, /*image_asset_path*/"EK", /*thumbnail_asset_path*/"EK", /*item_list_category_type*/8, /*scene_id*/32, /*banner_image_asset_path*/"", /*display_order*/14);
INSERT INTO `m_training_material` VALUES (/*id*/1932, /*name*/"k.item_name_1932", /*description*/"k.item_desc_1900", /*rarity*/3, /*image_asset_path*/"1\"", /*thumbnail_asset_path*/"1\"", /*item_list_category_type*/8, /*scene_id*/32, /*banner_image_asset_path*/"", /*display_order*/15);
INSERT INTO `m_training_material` VALUES (/*id*/1940, /*name*/"k.item_name_1940", /*description*/"k.item_desc_1900", /*rarity*/1, /*image_asset_path*/"Lm", /*thumbnail_asset_path*/"Lm", /*item_list_category_type*/8, /*scene_id*/32, /*banner_image_asset_path*/"", /*display_order*/16);
INSERT INTO `m_training_material` VALUES (/*id*/1941, /*name*/"k.item_name_1941", /*description*/"k.item_desc_1900", /*rarity*/2, /*image_asset_path*/"s|", /*thumbnail_asset_path*/"s|", /*item_list_category_type*/8, /*scene_id*/32, /*banner_image_asset_path*/"", /*display_order*/17);
INSERT INTO `m_training_material` VALUES (/*id*/1942, /*name*/"k.item_name_1942", /*description*/"k.item_desc_1900", /*rarity*/3, /*image_asset_path*/"?k", /*thumbnail_asset_path*/"?k", /*item_list_category_type*/8, /*scene_id*/32, /*banner_image_asset_path*/"", /*display_order*/18);
INSERT INTO `m_training_material` VALUES (/*id*/1950, /*name*/"k.item_name_1950", /*description*/"k.item_desc_1900", /*rarity*/1, /*image_asset_path*/"Ab", /*thumbnail_asset_path*/"Ab", /*item_list_category_type*/8, /*scene_id*/32, /*banner_image_asset_path*/"", /*display_order*/19);
INSERT INTO `m_training_material` VALUES (/*id*/1951, /*name*/"k.item_name_1951", /*description*/"k.item_desc_1900", /*rarity*/2, /*image_asset_path*/"wB", /*thumbnail_asset_path*/"wB", /*item_list_category_type*/8, /*scene_id*/32, /*banner_image_asset_path*/"", /*display_order*/20);
INSERT INTO `m_training_material` VALUES (/*id*/1952, /*name*/"k.item_name_1952", /*description*/"k.item_desc_1900", /*rarity*/3, /*image_asset_path*/"aR", /*thumbnail_asset_path*/"aR", /*item_list_category_type*/8, /*scene_id*/32, /*banner_image_asset_path*/"", /*display_order*/21);
INSERT INTO `m_training_material` VALUES (/*id*/1960, /*name*/"k.item_name_1960", /*description*/"k.item_desc_1960", /*rarity*/1, /*image_asset_path*/"=n", /*thumbnail_asset_path*/"=n", /*item_list_category_type*/8, /*scene_id*/32, /*banner_image_asset_path*/"", /*display_order*/22);
INSERT INTO `m_training_material` VALUES (/*id*/1961, /*name*/"k.item_name_1961", /*description*/"k.item_desc_1960", /*rarity*/2, /*image_asset_path*/"}J", /*thumbnail_asset_path*/"}J", /*item_list_category_type*/8, /*scene_id*/32, /*banner_image_asset_path*/"", /*display_order*/23);
INSERT INTO `m_training_material` VALUES (/*id*/1962, /*name*/"k.item_name_1962", /*description*/"k.item_desc_1960", /*rarity*/3, /*image_asset_path*/"_8", /*thumbnail_asset_path*/"_8", /*item_list_category_type*/8, /*scene_id*/32, /*banner_image_asset_path*/"", /*display_order*/24);
INSERT INTO `m_training_material` VALUES (/*id*/1970, /*name*/"k.item_name_1970", /*description*/"k.item_desc_1960", /*rarity*/1, /*image_asset_path*/"ME", /*thumbnail_asset_path*/"ME", /*item_list_category_type*/8, /*scene_id*/32, /*banner_image_asset_path*/"", /*display_order*/25);
INSERT INTO `m_training_material` VALUES (/*id*/1971, /*name*/"k.item_name_1971", /*description*/"k.item_desc_1960", /*rarity*/2, /*image_asset_path*/"sx", /*thumbnail_asset_path*/"sx", /*item_list_category_type*/8, /*scene_id*/32, /*banner_image_asset_path*/"", /*display_order*/26);
INSERT INTO `m_training_material` VALUES (/*id*/1972, /*name*/"k.item_name_1972", /*description*/"k.item_desc_1960", /*rarity*/3, /*image_asset_path*/"Bd", /*thumbnail_asset_path*/"Bd", /*item_list_category_type*/8, /*scene_id*/32, /*banner_image_asset_path*/"", /*display_order*/27);
INSERT INTO `m_training_material` VALUES (/*id*/8001, /*name*/"k.item_name_8001", /*description*/"k.item_desc_8000", /*rarity*/3, /*image_asset_path*/".Q", /*thumbnail_asset_path*/".Q", /*item_list_category_type*/16, /*scene_id*/32, /*banner_image_asset_path*/"", /*display_order*/28);
INSERT INTO `m_training_material` VALUES (/*id*/8002, /*name*/"k.item_name_8002", /*description*/"k.item_desc_8000", /*rarity*/3, /*image_asset_path*/"v^", /*thumbnail_asset_path*/"v^", /*item_list_category_type*/16, /*scene_id*/32, /*banner_image_asset_path*/"", /*display_order*/29);
INSERT INTO `m_training_material` VALUES (/*id*/8003, /*name*/"k.item_name_8003", /*description*/"k.item_desc_8000", /*rarity*/3, /*image_asset_path*/"ds", /*thumbnail_asset_path*/"ds", /*item_list_category_type*/16, /*scene_id*/32, /*banner_image_asset_path*/"", /*display_order*/30);
INSERT INTO `m_training_material` VALUES (/*id*/8004, /*name*/"k.item_name_8004", /*description*/"k.item_desc_8000", /*rarity*/3, /*image_asset_path*/"O:", /*thumbnail_asset_path*/"O:", /*item_list_category_type*/16, /*scene_id*/32, /*banner_image_asset_path*/"", /*display_order*/31);
INSERT INTO `m_training_material` VALUES (/*id*/8005, /*name*/"k.item_name_8005", /*description*/"k.item_desc_8000", /*rarity*/3, /*image_asset_path*/"s#", /*thumbnail_asset_path*/"s#", /*item_list_category_type*/16, /*scene_id*/32, /*banner_image_asset_path*/"", /*display_order*/32);
INSERT INTO `m_training_material` VALUES (/*id*/8006, /*name*/"k.item_name_8006", /*description*/"k.item_desc_8000", /*rarity*/3, /*image_asset_path*/"u,", /*thumbnail_asset_path*/"u,", /*item_list_category_type*/16, /*scene_id*/32, /*banner_image_asset_path*/"", /*display_order*/33);
INSERT INTO `m_training_material` VALUES (/*id*/8007, /*name*/"k.item_name_8007", /*description*/"k.item_desc_8000", /*rarity*/3, /*image_asset_path*/"-@", /*thumbnail_asset_path*/"-@", /*item_list_category_type*/16, /*scene_id*/32, /*banner_image_asset_path*/"", /*display_order*/34);
INSERT INTO `m_training_material` VALUES (/*id*/8008, /*name*/"k.item_name_8008", /*description*/"k.item_desc_8000", /*rarity*/3, /*image_asset_path*/"XV", /*thumbnail_asset_path*/"XV", /*item_list_category_type*/16, /*scene_id*/32, /*banner_image_asset_path*/"", /*display_order*/35);
INSERT INTO `m_training_material` VALUES (/*id*/8009, /*name*/"k.item_name_8009", /*description*/"k.item_desc_8000", /*rarity*/3, /*image_asset_path*/"`h", /*thumbnail_asset_path*/"`h", /*item_list_category_type*/16, /*scene_id*/32, /*banner_image_asset_path*/"", /*display_order*/36);
INSERT INTO `m_training_material` VALUES (/*id*/8101, /*name*/"k.item_name_8101", /*description*/"k.item_desc_8000", /*rarity*/3, /*image_asset_path*/"#[", /*thumbnail_asset_path*/"#[", /*item_list_category_type*/16, /*scene_id*/32, /*banner_image_asset_path*/"", /*display_order*/37);
INSERT INTO `m_training_material` VALUES (/*id*/8102, /*name*/"k.item_name_8102", /*description*/"k.item_desc_8000", /*rarity*/3, /*image_asset_path*/"mK", /*thumbnail_asset_path*/"mK", /*item_list_category_type*/16, /*scene_id*/32, /*banner_image_asset_path*/"", /*display_order*/38);
INSERT INTO `m_training_material` VALUES (/*id*/8103, /*name*/"k.item_name_8103", /*description*/"k.item_desc_8000", /*rarity*/3, /*image_asset_path*/"Ca", /*thumbnail_asset_path*/"Ca", /*item_list_category_type*/16, /*scene_id*/32, /*banner_image_asset_path*/"", /*display_order*/39);
INSERT INTO `m_training_material` VALUES (/*id*/8104, /*name*/"k.item_name_8104", /*description*/"k.item_desc_8000", /*rarity*/3, /*image_asset_path*/"Tm", /*thumbnail_asset_path*/"Tm", /*item_list_category_type*/16, /*scene_id*/32, /*banner_image_asset_path*/"", /*display_order*/40);
INSERT INTO `m_training_material` VALUES (/*id*/8105, /*name*/"k.item_name_8105", /*description*/"k.item_desc_8000", /*rarity*/3, /*image_asset_path*/"ZN", /*thumbnail_asset_path*/"ZN", /*item_list_category_type*/16, /*scene_id*/32, /*banner_image_asset_path*/"", /*display_order*/41);
INSERT INTO `m_training_material` VALUES (/*id*/8106, /*name*/"k.item_name_8106", /*description*/"k.item_desc_8000", /*rarity*/3, /*image_asset_path*/"P.", /*thumbnail_asset_path*/"P.", /*item_list_category_type*/16, /*scene_id*/32, /*banner_image_asset_path*/"", /*display_order*/42);
INSERT INTO `m_training_material` VALUES (/*id*/8107, /*name*/"k.item_name_8107", /*description*/"k.item_desc_8000", /*rarity*/3, /*image_asset_path*/"E4", /*thumbnail_asset_path*/"E4", /*item_list_category_type*/16, /*scene_id*/32, /*banner_image_asset_path*/"", /*display_order*/43);
INSERT INTO `m_training_material` VALUES (/*id*/8108, /*name*/"k.item_name_8108", /*description*/"k.item_desc_8000", /*rarity*/3, /*image_asset_path*/"rg", /*thumbnail_asset_path*/"rg", /*item_list_category_type*/16, /*scene_id*/32, /*banner_image_asset_path*/"", /*display_order*/44);
INSERT INTO `m_training_material` VALUES (/*id*/8109, /*name*/"k.item_name_8109", /*description*/"k.item_desc_8000", /*rarity*/3, /*image_asset_path*/"Iy", /*thumbnail_asset_path*/"Iy", /*item_list_category_type*/16, /*scene_id*/32, /*banner_image_asset_path*/"", /*display_order*/45);
INSERT INTO `m_training_material` VALUES (/*id*/8201, /*name*/"k.item_name_8201", /*description*/"k.item_desc_8000", /*rarity*/3, /*image_asset_path*/"6=", /*thumbnail_asset_path*/"6=", /*item_list_category_type*/16, /*scene_id*/32, /*banner_image_asset_path*/"", /*display_order*/46);
INSERT INTO `m_training_material` VALUES (/*id*/8202, /*name*/"k.item_name_8202", /*description*/"k.item_desc_8000", /*rarity*/3, /*image_asset_path*/"yP", /*thumbnail_asset_path*/"yP", /*item_list_category_type*/16, /*scene_id*/32, /*banner_image_asset_path*/"", /*display_order*/47);
INSERT INTO `m_training_material` VALUES (/*id*/8203, /*name*/"k.item_name_8203", /*description*/"k.item_desc_8000", /*rarity*/3, /*image_asset_path*/":W", /*thumbnail_asset_path*/":W", /*item_list_category_type*/16, /*scene_id*/32, /*banner_image_asset_path*/"", /*display_order*/48);
INSERT INTO `m_training_material` VALUES (/*id*/8204, /*name*/"k.item_name_8204", /*description*/"k.item_desc_8000", /*rarity*/3, /*image_asset_path*/"}1", /*thumbnail_asset_path*/"}1", /*item_list_category_type*/16, /*scene_id*/32, /*banner_image_asset_path*/"", /*display_order*/49);
INSERT INTO `m_training_material` VALUES (/*id*/8205, /*name*/"k.item_name_8205", /*description*/"k.item_desc_8000", /*rarity*/3, /*image_asset_path*/"@d", /*thumbnail_asset_path*/"@d", /*item_list_category_type*/16, /*scene_id*/32, /*banner_image_asset_path*/"", /*display_order*/50);
INSERT INTO `m_training_material` VALUES (/*id*/8206, /*name*/"k.item_name_8206", /*description*/"k.item_desc_8000", /*rarity*/3, /*image_asset_path*/"/A", /*thumbnail_asset_path*/"/A", /*item_list_category_type*/16, /*scene_id*/32, /*banner_image_asset_path*/"", /*display_order*/51);
INSERT INTO `m_training_material` VALUES (/*id*/8207, /*name*/"k.item_name_8207", /*description*/"k.item_desc_8000", /*rarity*/3, /*image_asset_path*/"0>", /*thumbnail_asset_path*/"0>", /*item_list_category_type*/16, /*scene_id*/32, /*banner_image_asset_path*/"", /*display_order*/52);
INSERT INTO `m_training_material` VALUES (/*id*/8208, /*name*/"k.item_name_8208", /*description*/"k.item_desc_8000", /*rarity*/3, /*image_asset_path*/"8H", /*thumbnail_asset_path*/"8H", /*item_list_category_type*/16, /*scene_id*/32, /*banner_image_asset_path*/"", /*display_order*/53);
INSERT INTO `m_training_material` VALUES (/*id*/8209, /*name*/"k.item_name_8209", /*description*/"k.item_desc_8000", /*rarity*/3, /*image_asset_path*/"c0", /*thumbnail_asset_path*/"c0", /*item_list_category_type*/16, /*scene_id*/32, /*banner_image_asset_path*/"", /*display_order*/54);
INSERT INTO `m_training_material` VALUES (/*id*/12101, /*name*/"k.item_name_12101", /*description*/"k.item_desc_12101", /*rarity*/1, /*image_asset_path*/"uz", /*thumbnail_asset_path*/"uz", /*item_list_category_type*/11, /*scene_id*/32, /*banner_image_asset_path*/"", /*display_order*/55);
INSERT INTO `m_training_material` VALUES (/*id*/12102, /*name*/"k.item_name_12102", /*description*/"k.item_desc_12101", /*rarity*/2, /*image_asset_path*/";]", /*thumbnail_asset_path*/";]", /*item_list_category_type*/11, /*scene_id*/32, /*banner_image_asset_path*/"", /*display_order*/56);
INSERT INTO `m_training_material` VALUES (/*id*/12103, /*name*/"k.item_name_12103", /*description*/"k.item_desc_12101", /*rarity*/3, /*image_asset_path*/"s0", /*thumbnail_asset_path*/"s0", /*item_list_category_type*/11, /*scene_id*/32, /*banner_image_asset_path*/"", /*display_order*/57);
INSERT INTO `m_training_material` VALUES (/*id*/12104, /*name*/"k.item_name_12104", /*description*/"k.item_desc_12101", /*rarity*/3, /*image_asset_path*/"%-", /*thumbnail_asset_path*/"%-", /*item_list_category_type*/11, /*scene_id*/32, /*banner_image_asset_path*/"", /*display_order*/58);
INSERT INTO `m_training_material` VALUES (/*id*/12201, /*name*/"k.item_name_12201", /*description*/"k.item_desc_12101", /*rarity*/1, /*image_asset_path*/"#4", /*thumbnail_asset_path*/"#4", /*item_list_category_type*/11, /*scene_id*/32, /*banner_image_asset_path*/"", /*display_order*/59);
INSERT INTO `m_training_material` VALUES (/*id*/12202, /*name*/"k.item_name_12202", /*description*/"k.item_desc_12101", /*rarity*/2, /*image_asset_path*/"5v", /*thumbnail_asset_path*/"5v", /*item_list_category_type*/11, /*scene_id*/32, /*banner_image_asset_path*/"", /*display_order*/60);
INSERT INTO `m_training_material` VALUES (/*id*/12203, /*name*/"k.item_name_12203", /*description*/"k.item_desc_12101", /*rarity*/3, /*image_asset_path*/"f<", /*thumbnail_asset_path*/"f<", /*item_list_category_type*/11, /*scene_id*/32, /*banner_image_asset_path*/"", /*display_order*/61);
INSERT INTO `m_training_material` VALUES (/*id*/12204, /*name*/"k.item_name_12204", /*description*/"k.item_desc_12101", /*rarity*/3, /*image_asset_path*/"N<", /*thumbnail_asset_path*/"N<", /*item_list_category_type*/11, /*scene_id*/32, /*banner_image_asset_path*/"", /*display_order*/62);
INSERT INTO `m_training_material` VALUES (/*id*/12301, /*name*/"k.item_name_12301", /*description*/"k.item_desc_12101", /*rarity*/1, /*image_asset_path*/"KP", /*thumbnail_asset_path*/"KP", /*item_list_category_type*/11, /*scene_id*/32, /*banner_image_asset_path*/"", /*display_order*/63);
INSERT INTO `m_training_material` VALUES (/*id*/12302, /*name*/"k.item_name_12302", /*description*/"k.item_desc_12101", /*rarity*/2, /*image_asset_path*/"K2", /*thumbnail_asset_path*/"K2", /*item_list_category_type*/11, /*scene_id*/32, /*banner_image_asset_path*/"", /*display_order*/64);
INSERT INTO `m_training_material` VALUES (/*id*/12303, /*name*/"k.item_name_12303", /*description*/"k.item_desc_12101", /*rarity*/3, /*image_asset_path*/"lW", /*thumbnail_asset_path*/"lW", /*item_list_category_type*/11, /*scene_id*/32, /*banner_image_asset_path*/"", /*display_order*/65);
INSERT INTO `m_training_material` VALUES (/*id*/12304, /*name*/"k.item_name_12304", /*description*/"k.item_desc_12101", /*rarity*/3, /*image_asset_path*/"u}", /*thumbnail_asset_path*/"u}", /*item_list_category_type*/11, /*scene_id*/32, /*banner_image_asset_path*/"", /*display_order*/66);
INSERT INTO `m_training_material` VALUES (/*id*/12401, /*name*/"k.item_name_12401", /*description*/"k.item_desc_12101", /*rarity*/1, /*image_asset_path*/"4!", /*thumbnail_asset_path*/"4!", /*item_list_category_type*/11, /*scene_id*/32, /*banner_image_asset_path*/"", /*display_order*/67);
INSERT INTO `m_training_material` VALUES (/*id*/12402, /*name*/"k.item_name_12402", /*description*/"k.item_desc_12101", /*rarity*/2, /*image_asset_path*/"j4", /*thumbnail_asset_path*/"j4", /*item_list_category_type*/11, /*scene_id*/32, /*banner_image_asset_path*/"", /*display_order*/68);
INSERT INTO `m_training_material` VALUES (/*id*/12403, /*name*/"k.item_name_12403", /*description*/"k.item_desc_12101", /*rarity*/3, /*image_asset_path*/"2-", /*thumbnail_asset_path*/"2-", /*item_list_category_type*/11, /*scene_id*/32, /*banner_image_asset_path*/"", /*display_order*/69);
INSERT INTO `m_training_material` VALUES (/*id*/12404, /*name*/"k.item_name_12404", /*description*/"k.item_desc_12101", /*rarity*/3, /*image_asset_path*/"pf", /*thumbnail_asset_path*/"pf", /*item_list_category_type*/11, /*scene_id*/32, /*banner_image_asset_path*/"", /*display_order*/70);
INSERT INTO `m_training_material` VALUES (/*id*/13101, /*name*/"k.item_name_13101", /*description*/"k.item_desc_12101", /*rarity*/1, /*image_asset_path*/"H/", /*thumbnail_asset_path*/"H/", /*item_list_category_type*/17, /*scene_id*/32, /*banner_image_asset_path*/"", /*display_order*/71);
INSERT INTO `m_training_material` VALUES (/*id*/13102, /*name*/"k.item_name_13102", /*description*/"k.item_desc_12101", /*rarity*/2, /*image_asset_path*/"E[", /*thumbnail_asset_path*/"E[", /*item_list_category_type*/17, /*scene_id*/32, /*banner_image_asset_path*/"", /*display_order*/72);
INSERT INTO `m_training_material` VALUES (/*id*/13103, /*name*/"k.item_name_13103", /*description*/"k.item_desc_12101", /*rarity*/3, /*image_asset_path*/"x+", /*thumbnail_asset_path*/"x+", /*item_list_category_type*/17, /*scene_id*/32, /*banner_image_asset_path*/"", /*display_order*/73);
INSERT INTO `m_training_material` VALUES (/*id*/13104, /*name*/"k.item_name_13104", /*description*/"k.item_desc_12101", /*rarity*/3, /*image_asset_path*/"?\"", /*thumbnail_asset_path*/"?\"", /*item_list_category_type*/17, /*scene_id*/32, /*banner_image_asset_path*/"", /*display_order*/74);
INSERT INTO `m_training_material` VALUES (/*id*/13201, /*name*/"k.item_name_13201", /*description*/"k.item_desc_12101", /*rarity*/1, /*image_asset_path*/"SP", /*thumbnail_asset_path*/"SP", /*item_list_category_type*/17, /*scene_id*/32, /*banner_image_asset_path*/"", /*display_order*/75);
INSERT INTO `m_training_material` VALUES (/*id*/13202, /*name*/"k.item_name_13202", /*description*/"k.item_desc_12101", /*rarity*/2, /*image_asset_path*/"V2", /*thumbnail_asset_path*/"V2", /*item_list_category_type*/17, /*scene_id*/32, /*banner_image_asset_path*/"", /*display_order*/76);
INSERT INTO `m_training_material` VALUES (/*id*/13203, /*name*/"k.item_name_13203", /*description*/"k.item_desc_12101", /*rarity*/3, /*image_asset_path*/">?", /*thumbnail_asset_path*/">?", /*item_list_category_type*/17, /*scene_id*/32, /*banner_image_asset_path*/"", /*display_order*/77);
INSERT INTO `m_training_material` VALUES (/*id*/13204, /*name*/"k.item_name_13204", /*description*/"k.item_desc_12101", /*rarity*/3, /*image_asset_path*/";3", /*thumbnail_asset_path*/";3", /*item_list_category_type*/17, /*scene_id*/32, /*banner_image_asset_path*/"", /*display_order*/78);
INSERT INTO `m_training_material` VALUES (/*id*/13301, /*name*/"k.item_name_13301", /*description*/"k.item_desc_12101", /*rarity*/1, /*image_asset_path*/"NX", /*thumbnail_asset_path*/"NX", /*item_list_category_type*/17, /*scene_id*/32, /*banner_image_asset_path*/"", /*display_order*/79);
INSERT INTO `m_training_material` VALUES (/*id*/13302, /*name*/"k.item_name_13302", /*description*/"k.item_desc_12101", /*rarity*/2, /*image_asset_path*/"~F", /*thumbnail_asset_path*/"~F", /*item_list_category_type*/17, /*scene_id*/32, /*banner_image_asset_path*/"", /*display_order*/80);
INSERT INTO `m_training_material` VALUES (/*id*/13303, /*name*/"k.item_name_13303", /*description*/"k.item_desc_12101", /*rarity*/3, /*image_asset_path*/"}l", /*thumbnail_asset_path*/"}l", /*item_list_category_type*/17, /*scene_id*/32, /*banner_image_asset_path*/"", /*display_order*/81);
INSERT INTO `m_training_material` VALUES (/*id*/13304, /*name*/"k.item_name_13304", /*description*/"k.item_desc_12101", /*rarity*/3, /*image_asset_path*/"fc", /*thumbnail_asset_path*/"fc", /*item_list_category_type*/17, /*scene_id*/32, /*banner_image_asset_path*/"", /*display_order*/82);
INSERT INTO `m_training_material` VALUES (/*id*/13401, /*name*/"k.item_name_13401", /*description*/"k.item_desc_12101", /*rarity*/1, /*image_asset_path*/"D$", /*thumbnail_asset_path*/"D$", /*item_list_category_type*/17, /*scene_id*/32, /*banner_image_asset_path*/"", /*display_order*/83);
INSERT INTO `m_training_material` VALUES (/*id*/13402, /*name*/"k.item_name_13402", /*description*/"k.item_desc_12101", /*rarity*/2, /*image_asset_path*/"tj", /*thumbnail_asset_path*/"tj", /*item_list_category_type*/17, /*scene_id*/32, /*banner_image_asset_path*/"", /*display_order*/84);
INSERT INTO `m_training_material` VALUES (/*id*/13403, /*name*/"k.item_name_13403", /*description*/"k.item_desc_12101", /*rarity*/3, /*image_asset_path*/"WS", /*thumbnail_asset_path*/"WS", /*item_list_category_type*/17, /*scene_id*/32, /*banner_image_asset_path*/"", /*display_order*/85);
INSERT INTO `m_training_material` VALUES (/*id*/13404, /*name*/"k.item_name_13404", /*description*/"k.item_desc_12101", /*rarity*/3, /*image_asset_path*/"rG", /*thumbnail_asset_path*/"rG", /*item_list_category_type*/17, /*scene_id*/32, /*banner_image_asset_path*/"", /*display_order*/86);
